# Conjunto de datos.
El conjunto principal de datos proviene de la Organización Mundial de la Salud [OMS](https://www.who.int/data/gho/data/themes/mortality-and-global-health-estimates/global-health-estimates-leading-causes-of-dalys/) [^1]. Los DALYs (*Disability-adjusted life years*) se reportan a tres escalas diferentes: global, regional y a nivel de país. Para este análisis nos interesa, por el momento, los datos reportados por país desde 2000-2021 de los cuales sólo hay datos para los años 2000, 2010, 2015, 2019, 2020 y 2021 (que se debe a que estimados anteriores no se pueden comparar con los actuales). 

Al descargar los archivos ghe2021_daly_bycountry_**** de los años respectivos, fueron movidos a la subcarpeta data_raw, en la subcarpeta de DALYs.

## A. Se cargan las librerías necesarias

In [1]:
import pandas as pd
import numpy as np
import pickle

## B. Se cargan los datos que se buscan analizar.

In [2]:
file_paths = {
    2000: 'data_raw/datos_analisis/DALYs/ghe2021_daly_bycountry_2000.xlsx',
    2010: 'data_raw/datos_analisis/DALYs/ghe2021_daly_bycountry_2010.xlsx',
    2015: 'data_raw/datos_analisis/DALYs/ghe2021_daly_bycountry_2015.xlsx',
    2019: 'data_raw/datos_analisis/DALYs/ghe2021_daly_bycountry_2019.xlsx',
    2020: 'data_raw/datos_analisis/DALYs/ghe2021_daly_bycountry_2020.xlsx',
    2021: 'data_raw/datos_analisis/DALYs/ghe2021_daly_bycountry_2021.xlsx'
}

# Intervenciones médicas por NTDs
df_interNTD = pd.read_csv('data_raw/datos_analisis/interventions/interventions-ntds-sdgs.csv', encoding='latin-1')

# GDP per capita
df_GDP = pd.read_csv('data_raw/datos_analisis/gdp-per-capita-worldbank/gdp-per-capita.csv', encoding='latin-1')

# Coeficiente Gini
df_gini = pd.read_csv('data_raw/datos_analisis/gini-coefficient-after-tax/gini-coefficient.csv', encoding='latin-1')
    
# Precipitación total por país.
df_precipitacion = pd.read_csv('data_raw/datos_analisis/total_yearly_precip/GDL-Total-Yearly-Precipitation-(m)-data.csv', encoding='latin-1')

# Temperatura anual promedio.
df_temperatura = pd.read_csv('data_raw/datos_analisis/yearly_average_temp/GDL-Yearly-Average-Surface-Temperature-(ºC)-data.csv', encoding='latin-1')

# Humedad relativa promedio anual por país.
df_humedad = pd.read_csv('data_raw/datos_analisis/yearly_average_humidity/GDL-Yearly-Average-Relative-Humidity-(_)-data.csv', encoding='latin-1')

# Emisiones de CO2
df_emisiones = pd.read_csv('data_raw\datos_analisis\emisiones_CO2\GDL-Total-Yearly-CO2-Emissions-(ton)-data.csv', encoding='latin-1')

## Índices de desarrollo humano.

development_paths = {
    # HDI (Índice de Desarrollo Humano)
    'hdi_masc': 'data_raw/datos_analisis/human_development_indexes/GDL-Subnational-HDI-men-data.csv',
    'hdi_fem': 'data_raw/datos_analisis/human_development_indexes/GDL-Subnational-HDI-women-data.csv',
    
    # Educación
    'educacion_masc': 'data_raw/datos_analisis/human_development_indexes/GDL-Educational-index-men-data.csv',
    'educacion_fem': 'data_raw/datos_analisis/human_development_indexes/GDL-Educational-index-women-data.csv',
    
    # Salud
    'salud_masc': 'data_raw/datos_analisis/human_development_indexes/GDL-Health-index-men-data.csv',
    'salud_fem': 'data_raw/datos_analisis/human_development_indexes/GDL-Health-index-women-data.csv',
    
    # Ingresos
    'ingresos_masc': 'data_raw/datos_analisis/human_development_indexes/GDL-Income-index-men-data.csv',
    'ingresos_fem': 'data_raw/datos_analisis/human_development_indexes/GDL-Income-index-women-data.csv',
    
    # Esperanza de vida
    'expectancy_masc': 'data_raw/datos_analisis/human_development_indexes/GDL-Life-expectancy-men-data.csv',
    'expectancy_fem': 'data_raw/datos_analisis/human_development_indexes/GDL-Life-expectancy-women-data.csv',
}

<>:29: SyntaxWarning: invalid escape sequence '\d'
<>:29: SyntaxWarning: invalid escape sequence '\d'
C:\Users\troop\AppData\Local\Temp\ipykernel_7024\1653959012.py:29: SyntaxWarning: invalid escape sequence '\d'
  df_emisiones = pd.read_csv('data_raw\datos_analisis\emisiones_CO2\GDL-Total-Yearly-CO2-Emissions-(ton)-data.csv', encoding='latin-1')

## C. Catálogo para enfermedades

In [ ]:
# !!!!!!!!!!!!!!!!! Correr una sola vez para editar manualmente !!!!!!!!!!!!!!!!


# Se carga cualesquiera de las hojas de DALYs
file_cat = file_paths[2000]
edad_cat = '0-4'
cat_enfermedades = pd.read_excel (
    file_cat,
    sheet_name=edad_cat,
    skiprows=range(0, 227)
)

columns_cat = cat_enfermedades.columns[:7]

# Extraer sólo las primeras 7 columnas.
catalogo = cat_enfermedades.iloc[:, :7].copy()  # Las primeras 6 columnas
catalogo.columns = ['sexo', 'codigo_ghe', 'categoria_principal', 
                    'categoria_nivel1', 'categoria_nivel2', 'causa', 'Country or area (See Notes for explanation of colour codes)']

for col in catalogo.columns:
    catalogo[col] = catalogo[col].ffill()

catalogo = catalogo.dropna(subset=['codigo_ghe'])

catalogo.to_csv('data_raw/DALYs_catalogo_enfermedades.csv', index=False)

La edición manual consiste en remover las ambiguedades en la hoja dadas por la estructura de los datos iniciales. La categroría principal

In [3]:
catalogo = pd.read_csv('data_raw/DALYs_catalogo_enfermedades.csv', encoding='latin1')
display( catalogo.head() )

,sexo,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa
0,Males,0.0,All Causes,NaN,NaN,NaN
1,Males,10.0,"I.Communicable, maternal, perinatal and nutrit...",NaN,NaN,NaN
2,Males,20.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,NaN,NaN
3,Males,30.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,1.Tuberculosis,Tuberculosis
4,Males,40.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,2.STDs excluding HIV,NaN

## D. Remodelación de Datos

In [4]:
años = [2000, 2010, 2015, 2019, 2020, 2021]

col_names = ['sexo', 'codigo_ghe', 'categoria_principal', 'categoria_nivel1', 'categoria_nivel2', 'causa',
             'Country or area (See Notes for explanation of colour codes)', 
             'Afghanistan', 'Albania', 'Algeria', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 
             'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 
             'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia (Plurinational State of)', 'Bosnia and Herzegovina', 
             'Botswana', 'Brazil', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 
             'Cameroon', 'Canada', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo', 
             'Costa Rica', "Côte d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Czechia', "Democratic People's Republic of Korea", 
             'Democratic Republic of the Congo', 'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador', 
             'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia', 
             'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 
             'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran (Islamic Republic of)', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 
             'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan', "Lao People's Democratic Republic", 'Latvia', 'Lebanon', 'Lesotho', 
             'Liberia', 'Libya', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Mauritania', 'Mauritius', 
             'Mexico', 'Micronesia (Federated States of)', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nepal', 'Netherlands', 
             'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Macedonia', 'Norway', 'occupied Palestinian territory, including east Jerusalem', 'Oman', 
             'Pakistan', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar', 'Republic of Korea', 'Republic of Moldova', 
             'Romania', 'Russian Federation', 'Rwanda', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 
             'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 
             'Sweden', 'Switzerland', 'Syrian Arab Republic', 'Tajikistan', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Türkiye', 'Turkmenistan', 
             'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United Republic of Tanzania', 'United States of America', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela (Bolivarian Republic of)', 
             'Viet Nam', 'Yemen', 'Zambia', 'Zimbabwe']

edades = ['0-4', '5-14','15-29', '30-49', '50-59', '60-69', '70+']

col_order = ['año', 'pais', 'codigo_pais', 'codigo_ghe', 'categoria_principal', 'categoria_nivel1', 'categoria_nivel2', 'causa', 
             'sexo', 'edad', 'DALYs']

# Nos interesan los códigos de las enfermedades correspondientes a Tropicales Desantendidas:
# enfermedad de Chagas, dengue, equinococosis, frambesia o pian (treponematosis),
# fascioliasis, tripanosomiasis africana, leishmaniasis, lepra, filariasis linfática, oncocercosis, rabia,
# esquistosomiasis, geohelmintiasis, cisticercosis, tracoma, sarna y otros ectoparásitos, micetoma y
# micosis profundas. Se agregará Malaria.
codigos_ghe = [ 210, 220, 230, 240, 250, 260, 270, 280, 285, 295, 300, 310, 315, 320, 340, 330, 350, 360, 362, 365]

codigos_paises = {
    'Afghanistan': 'AFG', 'Albania': 'ALB', 'Algeria': 'DZA', 'Angola': 'AGO',
    'Antigua and Barbuda': 'ATG', 'Argentina': 'ARG', 'Armenia': 'ARM',
    'Australia': 'AUS', 'Austria': 'AUT', 'Azerbaijan': 'AZE', 'Bahamas': 'BHS',
    'Bahrain': 'BHR', 'Bangladesh': 'BGD', 'Barbados': 'BRB', 'Belarus': 'BLR',
    'Belgium': 'BEL', 'Belize': 'BLZ', 'Benin': 'BEN', 'Bhutan': 'BTN',
    'Bolivia (Plurinational State of)': 'BOL', 'Bosnia and Herzegovina': 'BIH',
    'Botswana': 'BWA', 'Brazil': 'BRA', 'Brunei Darussalam': 'BRN',
    'Bulgaria': 'BGR', 'Burkina Faso': 'BFA', 'Burundi': 'BDI', 'Cabo Verde': 'CPV',
    'Cambodia': 'KHM', 'Cameroon': 'CMR', 'Canada': 'CAN',
    'Central African Republic': 'CAF', 'Chad': 'TCD', 'Chile': 'CHL',
    'China': 'CHN', 'Colombia': 'COL', 'Comoros': 'COM', 'Congo': 'COG',
    'Costa Rica': 'CRI', "Côte d'Ivoire": 'CIV', 'Croatia': 'HRV', 'Cuba': 'CUB',
    'Cyprus': 'CYP', 'Czechia': 'CZE', 'Democratic People\'s Republic of Korea': 'PRK',
    'Democratic Republic of the Congo': 'COD', 'Denmark': 'DNK', 'Djibouti': 'DJI',
    'Dominican Republic': 'DOM', 'Ecuador': 'ECU', 'Egypt': 'EGY',
    'El Salvador': 'SLV', 'Equatorial Guinea': 'GNQ', 'Eritrea': 'ERI',
    'Estonia': 'EST', 'Eswatini': 'SWZ', 'Ethiopia': 'ETH', 'Fiji': 'FJI',
    'Finland': 'FIN', 'France': 'FRA', 'Gabon': 'GAB', 'Gambia': 'GMB',
    'Georgia': 'GEO', 'Germany': 'DEU', 'Ghana': 'GHA', 'Greece': 'GRC',
    'Grenada': 'GRD', 'Guatemala': 'GTM', 'Guinea': 'GIN', 'Guinea-Bissau': 'GNB',
    'Guyana': 'GUY', 'Haiti': 'HTI', 'Honduras': 'HND', 'Hungary': 'HUN',
    'Iceland': 'ISL', 'India': 'IND', 'Indonesia': 'IDN',
    'Iran (Islamic Republic of)': 'IRN', 'Iraq': 'IRQ', 'Ireland': 'IRL',
    'Israel': 'ISR', 'Italy': 'ITA', 'Jamaica': 'JAM', 'Japan': 'JPN',
    'Jordan': 'JOR', 'Kazakhstan': 'KAZ', 'Kenya': 'KEN', 'Kiribati': 'KIR',
    'Kuwait': 'KWT', 'Kyrgyzstan': 'KGZ', 'Lao People\'s Democratic Republic': 'LAO',
    'Latvia': 'LVA', 'Lebanon': 'LBN', 'Lesotho': 'LSO', 'Liberia': 'LBR',
    'Libya': 'LBY', 'Lithuania': 'LTU', 'Luxembourg': 'LUX', 'Madagascar': 'MDG',
    'Malawi': 'MWI', 'Malaysia': 'MYS', 'Maldives': 'MDV', 'Mali': 'MLI',
    'Malta': 'MLT', 'Mauritania': 'MRT', 'Mauritius': 'MUS', 'Mexico': 'MEX',
    'Micronesia (Federated States of)': 'FSM', 'Mongolia': 'MNG', 'Montenegro': 'MNE',
    'Morocco': 'MAR', 'Mozambique': 'MOZ', 'Myanmar': 'MMR', 'Namibia': 'NAM',
    'Nepal': 'NPL', 'Netherlands': 'NLD', 'New Zealand': 'NZL', 'Nicaragua': 'NIC',
    'Niger': 'NER', 'Nigeria': 'NGA', 'North Macedonia': 'MKD', 'Norway': 'NOR',
    'occupied Palestinian territory, including east Jerusalem': 'PSE', 'Oman': 'OMN',
    'Pakistan': 'PAK', 'Panama': 'PAN', 'Papua New Guinea': 'PNG', 'Paraguay': 'PRY',
    'Peru': 'PER', 'Philippines': 'PHL', 'Poland': 'POL', 'Portugal': 'PRT',
    'Puerto Rico': 'PRI', 'Qatar': 'QAT', 'Republic of Korea': 'KOR',
    'Republic of Moldova': 'MDA', 'Romania': 'ROU', 'Russian Federation': 'RUS',
    'Rwanda': 'RWA', 'Saint Lucia': 'LCA', 'Saint Vincent and the Grenadines': 'VCT',
    'Samoa': 'WSM', 'Sao Tome and Principe': 'STP', 'Saudi Arabia': 'SAU',
    'Senegal': 'SEN', 'Serbia': 'SRB', 'Seychelles': 'SYC', 'Sierra Leone': 'SLE',
    'Singapore': 'SGP', 'Slovakia': 'SVK', 'Slovenia': 'SVN', 'Solomon Islands': 'SLB',
    'Somalia': 'SOM', 'South Africa': 'ZAF', 'South Sudan': 'SSD', 'Spain': 'ESP',
    'Sri Lanka': 'LKA', 'Sudan': 'SDN', 'Suriname': 'SUR', 'Sweden': 'SWE',
    'Switzerland': 'CHE', 'Syrian Arab Republic': 'SYR', 'Tajikistan': 'TJK',
    'Thailand': 'THA', 'Timor-Leste': 'TLS', 'Togo': 'TGO', 'Tonga': 'TON',
    'Trinidad and Tobago': 'TTO', 'Tunisia': 'TUN', 'Türkiye': 'TUR',
    'Turkmenistan': 'TKM', 'Uganda': 'UGA', 'Ukraine': 'UKR',
    'United Arab Emirates': 'ARE', 'United Kingdom': 'GBR',
    'United Republic of Tanzania': 'TZA', 'United States of America': 'USA',
    'Uruguay': 'URY', 'Uzbekistan': 'UZB', 'Vanuatu': 'VUT',
    'Venezuela (Bolivarian Republic of)': 'VEN', 'Viet Nam': 'VNM',
    'Yemen': 'YEM', 'Zambia': 'ZMB', 'Zimbabwe': 'ZWE'
}

all_dfs = {}
for año in años:
    file = file_paths[año]
    df_edades = []

    for edad in edades: 
        # Cargar archivos
        print(f"Año: {año}, Edad: {edad}")
        df = pd.read_excel(
            file,
            sheet_name=edad,
            skiprows=range(0, 226),
            # nrows=10 # Quitar para procesar todos los datos
        )
        
        # Se renombran las columnas 
        df.columns = col_names

        # Selección de columnas 
        df = df.drop(columns = ['categoria_principal', 'categoria_nivel1', 'categoria_nivel2', 'causa', 'Country or area (See Notes for explanation of colour codes)'])

        # Transformación a formato tidy
        df = pd.melt(df, id_vars=['codigo_ghe', 'sexo'], var_name='pais', value_name='DALYs')

        # Se agrega el año
        df['año'] = año
        # Se agrega la edad
        df['edad'] = edad
        # Se agrega el código de cada país
        df['codigo_pais'] = df['pais'].map(codigos_paises)

        # Merge con el catálogo de enfermedades de acuerdo con el sexo y el código GHE
        df = pd.merge(df, catalogo, on=['sexo', 'codigo_ghe'], how='inner')

        # Selección de filas de acuerdo con el código de enfermedades.
        df = df[df['codigo_ghe'].isin(codigos_ghe)]

        # Se ordena
        df = df[col_order]
        display(df)

        # Dataframe para edades, dado que se encuentran separadas las hojas
        df_edades.append(df)
    
    # FUERA del bucle de edades, pero DENTRO del bucle de años
    df_anual = pd.concat(df_edades, ignore_index=True)

    # Resultados
    df_anual.to_csv(f"data_clean/DALYs_clean_{año}.csv", index=False)
    all_dfs[año] = df_anual

# Concatenación de todos los Dataframes
df_unificado = pd.concat(all_dfs.values(), ignore_index=True)
df_unificado.to_csv('data_clean/DALYs_clean_unificado.csv', index=False)

display( df_unificado )

Año: 2000, Edad: 0-4

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2000,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,0-4,3.660181e+01
26,2000,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,0-4,1.237099e+01
27,2000,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,0-4,0.000000e+00
28,2000,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,0-4,0.000000e+00
29,2000,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,0-4,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2000,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,0-4,1.435696e-01
80486,2000,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,0-4,1.135587e-08
80487,2000,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,0-4,6.626784e-01
80488,2000,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,0-4,0.000000e+00
80489,2000,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,0-4,4.539695e-06

Año: 2000, Edad: 5-14

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2000,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,5-14,1.624601e+01
26,2000,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,5-14,9.541708e-01
27,2000,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,5-14,0.000000e+00
28,2000,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,5-14,0.000000e+00
29,2000,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,5-14,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2000,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,5-14,6.084173e-03
80486,2000,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,5-14,1.323621e-07
80487,2000,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,5-14,2.643464e+00
80488,2000,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,5-14,0.000000e+00
80489,2000,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,5-14,1.190710e-04

Año: 2000, Edad: 15-29

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2000,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,15-29,1.972535e+01
26,2000,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,15-29,1.023784e+01
27,2000,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,15-29,0.000000e+00
28,2000,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,15-29,0.000000e+00
29,2000,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,15-29,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2000,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,15-29,1.348450e-02
80486,2000,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,15-29,2.212057e-07
80487,2000,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,15-29,3.029439e+00
80488,2000,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,15-29,0.000000e+00
80489,2000,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,15-29,7.172600e-04

Año: 2000, Edad: 30-49

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2000,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,30-49,1.332466e+01
26,2000,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,30-49,4.798007e+00
27,2000,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,30-49,0.000000e+00
28,2000,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,30-49,0.000000e+00
29,2000,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,30-49,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2000,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,30-49,2.418401e-03
80486,2000,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,30-49,5.126528e-08
80487,2000,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,30-49,8.318943e-01
80488,2000,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,30-49,0.000000e+00
80489,2000,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,30-49,1.022055e-03

Año: 2000, Edad: 50-59

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2000,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,50-59,4.629043e+00
26,2000,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,50-59,1.029030e+00
27,2000,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,50-59,0.000000e+00
28,2000,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,50-59,0.000000e+00
29,2000,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,50-59,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2000,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,50-59,8.684071e-04
80486,2000,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,50-59,8.894782e-09
80487,2000,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,50-59,2.602681e-01
80488,2000,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,50-59,0.000000e+00
80489,2000,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,50-59,5.711038e-04

Año: 2000, Edad: 60-69

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2000,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,60-69,3.352437e+00
26,2000,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,60-69,8.029436e-01
27,2000,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,60-69,0.000000e+00
28,2000,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,60-69,0.000000e+00
29,2000,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,60-69,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2000,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,60-69,8.213648e-04
80486,2000,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,60-69,4.657208e-09
80487,2000,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,60-69,1.904054e-01
80488,2000,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,60-69,0.000000e+00
80489,2000,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,60-69,5.060477e-04

Año: 2000, Edad: 70+

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2000,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,70+,1.685779e+00
26,2000,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,70+,2.021278e-01
27,2000,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,70+,0.000000e+00
28,2000,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,70+,0.000000e+00
29,2000,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,70+,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2000,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,70+,1.330534e-03
80486,2000,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,70+,2.646380e-09
80487,2000,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,70+,1.444745e-01
80488,2000,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,70+,0.000000e+00
80489,2000,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,70+,4.892579e-04

Año: 2010, Edad: 0-4

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2010,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,0-4,1.946223e+01
26,2010,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,0-4,3.167376e+00
27,2010,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,0-4,0.000000e+00
28,2010,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,0-4,0.000000e+00
29,2010,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,0-4,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2010,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,0-4,6.086966e-01
80486,2010,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,0-4,9.485186e-09
80487,2010,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,0-4,9.750076e-01
80488,2010,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,0-4,0.000000e+00
80489,2010,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,0-4,8.629355e-06

Año: 2010, Edad: 5-14

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2010,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,5-14,2.060825e+01
26,2010,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,5-14,4.987754e-01
27,2010,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,5-14,0.000000e+00
28,2010,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,5-14,0.000000e+00
29,2010,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,5-14,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2010,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,5-14,3.275983e-02
80486,2010,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,5-14,1.074647e-07
80487,2010,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,5-14,3.661542e+00
80488,2010,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,5-14,0.000000e+00
80489,2010,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,5-14,1.999522e-04

Año: 2010, Edad: 15-29

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2010,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,15-29,1.424489e+01
26,2010,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,15-29,2.227995e+00
27,2010,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,15-29,0.000000e+00
28,2010,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,15-29,0.000000e+00
29,2010,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,15-29,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2010,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,15-29,2.669069e-02
80486,2010,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,15-29,1.643217e-07
80487,2010,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,15-29,3.297661e+00
80488,2010,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,15-29,0.000000e+00
80489,2010,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,15-29,1.235941e-03

Año: 2010, Edad: 30-49

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2010,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,30-49,1.111150e+01
26,2010,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,30-49,8.921433e-01
27,2010,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,30-49,0.000000e+00
28,2010,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,30-49,0.000000e+00
29,2010,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,30-49,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2010,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,30-49,8.895981e-03
80486,2010,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,30-49,5.423158e-08
80487,2010,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,30-49,1.246562e+00
80488,2010,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,30-49,0.000000e+00
80489,2010,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,30-49,1.960580e-03

Año: 2010, Edad: 50-59

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2010,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,50-59,3.766044e+00
26,2010,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,50-59,1.831545e-01
27,2010,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,50-59,0.000000e+00
28,2010,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,50-59,0.000000e+00
29,2010,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,50-59,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2010,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,50-59,3.727107e-03
80486,2010,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,50-59,7.795023e-09
80487,2010,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,50-59,3.608844e-01
80488,2010,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,50-59,0.000000e+00
80489,2010,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,50-59,1.037364e-03

Año: 2010, Edad: 60-69

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2010,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,60-69,2.722353e+00
26,2010,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,60-69,1.416153e-01
27,2010,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,60-69,0.000000e+00
28,2010,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,60-69,0.000000e+00
29,2010,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,60-69,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2010,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,60-69,2.733212e-03
80486,2010,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,60-69,3.993972e-09
80487,2010,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,60-69,2.542643e-01
80488,2010,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,60-69,0.000000e+00
80489,2010,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,60-69,8.729454e-04

Año: 2010, Edad: 70+

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2010,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,70+,1.678267e+00
26,2010,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,70+,4.157559e-02
27,2010,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,70+,0.000000e+00
28,2010,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,70+,0.000000e+00
29,2010,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,70+,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2010,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,70+,3.128704e-03
80486,2010,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,70+,1.968565e-09
80487,2010,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,70+,1.725448e-01
80488,2010,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,70+,0.000000e+00
80489,2010,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,70+,7.874362e-04

Año: 2015, Edad: 0-4

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2015,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,0-4,1.274540e+01
26,2015,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,0-4,2.527338e+00
27,2015,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,0-4,0.000000e+00
28,2015,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,0-4,0.000000e+00
29,2015,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,0-4,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2015,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,0-4,6.248244e-01
80486,2015,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,0-4,1.242074e-08
80487,2015,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,0-4,8.918517e-01
80488,2015,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,0-4,0.000000e+00
80489,2015,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,0-4,7.952200e-06

Año: 2015, Edad: 5-14

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2015,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,5-14,1.836532e+01
26,2015,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,5-14,5.309711e-01
27,2015,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,5-14,0.000000e+00
28,2015,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,5-14,0.000000e+00
29,2015,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,5-14,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2015,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,5-14,6.534768e-02
80486,2015,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,5-14,1.360866e-07
80487,2015,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,5-14,3.221587e+00
80488,2015,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,5-14,0.000000e+00
80489,2015,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,5-14,1.781328e-04

Año: 2015, Edad: 15-29

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2015,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,15-29,1.648321e+01
26,2015,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,15-29,2.450293e+00
27,2015,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,15-29,0.000000e+00
28,2015,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,15-29,0.000000e+00
29,2015,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,15-29,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2015,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,15-29,1.714578e-02
80486,2015,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,15-29,1.782141e-07
80487,2015,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,15-29,2.528158e+00
80488,2015,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,15-29,0.000000e+00
80489,2015,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,15-29,8.939088e-04

Año: 2015, Edad: 30-49

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2015,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,30-49,1.091526e+01
26,2015,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,30-49,8.666053e-01
27,2015,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,30-49,0.000000e+00
28,2015,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,30-49,0.000000e+00
29,2015,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,30-49,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2015,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,30-49,1.819203e-02
80486,2015,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,30-49,7.955868e-08
80487,2015,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,30-49,1.303100e+00
80488,2015,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,30-49,0.000000e+00
80489,2015,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,30-49,2.062724e-03

Año: 2015, Edad: 50-59

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2015,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,50-59,3.371587e+00
26,2015,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,50-59,2.448375e-01
27,2015,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,50-59,0.000000e+00
28,2015,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,50-59,0.000000e+00
29,2015,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,50-59,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2015,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,50-59,3.675861e-03
80486,2015,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,50-59,8.612666e-09
80487,2015,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,50-59,2.811791e-01
80488,2015,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,50-59,0.000000e+00
80489,2015,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,50-59,8.004658e-04

Año: 2015, Edad: 60-69

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2015,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,60-69,2.346248e+00
26,2015,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,60-69,1.326931e-01
27,2015,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,60-69,0.000000e+00
28,2015,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,60-69,0.000000e+00
29,2015,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,60-69,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2015,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,60-69,3.627433e-03
80486,2015,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,60-69,5.837256e-09
80487,2015,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,60-69,2.617442e-01
80488,2015,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,60-69,0.000000e+00
80489,2015,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,60-69,8.849906e-04

Año: 2015, Edad: 70+

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2015,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,70+,1.560879e+00
26,2015,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,70+,4.713967e-02
27,2015,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,70+,0.000000e+00
28,2015,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,70+,0.000000e+00
29,2015,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,70+,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2015,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,70+,3.557916e-03
80486,2015,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,70+,2.475770e-09
80487,2015,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,70+,1.527221e-01
80488,2015,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,70+,0.000000e+00
80489,2015,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,70+,6.843411e-04

Año: 2019, Edad: 0-4

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2019,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,0-4,1.120774e+01
26,2019,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,0-4,2.470153e+00
27,2019,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,0-4,0.000000e+00
28,2019,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,0-4,0.000000e+00
29,2019,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,0-4,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2019,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,0-4,5.324108e-01
80486,2019,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,0-4,1.141605e-08
80487,2019,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,0-4,6.054710e-01
80488,2019,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,0-4,0.000000e+00
80489,2019,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,0-4,6.132609e-06

Año: 2019, Edad: 5-14

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2019,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,5-14,1.800115e+01
26,2019,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,5-14,5.237163e-01
27,2019,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,5-14,0.000000e+00
28,2019,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,5-14,0.000000e+00
29,2019,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,5-14,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2019,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,5-14,9.918751e-02
80486,2019,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,5-14,1.419487e-07
80487,2019,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,5-14,2.501482e+00
80488,2019,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,5-14,0.000000e+00
80489,2019,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,5-14,1.538698e-04

Año: 2019, Edad: 15-29

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2019,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,15-29,1.925003e+01
26,2019,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,15-29,2.409475e+00
27,2019,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,15-29,0.000000e+00
28,2019,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,15-29,0.000000e+00
29,2019,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,15-29,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2019,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,15-29,1.792889e-02
80486,2019,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,15-29,1.795505e-07
80487,2019,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,15-29,1.900395e+00
80488,2019,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,15-29,0.000000e+00
80489,2019,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,15-29,7.219530e-04

Año: 2019, Edad: 30-49

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2019,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,30-49,1.206965e+01
26,2019,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,30-49,8.381972e-01
27,2019,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,30-49,0.000000e+00
28,2019,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,30-49,0.000000e+00
29,2019,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,30-49,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2019,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,30-49,2.319323e-02
80486,2019,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,30-49,8.440119e-08
80487,2019,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,30-49,1.059105e+00
80488,2019,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,30-49,0.000000e+00
80489,2019,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,30-49,1.994144e-03

Año: 2019, Edad: 50-59

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2019,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,50-59,3.599220e+00
26,2019,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,50-59,1.935253e-01
27,2019,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,50-59,0.000000e+00
28,2019,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,50-59,0.000000e+00
29,2019,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,50-59,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2019,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,50-59,3.763899e-03
80486,2019,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,50-59,8.871264e-09
80487,2019,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,50-59,2.103295e-01
80488,2019,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,50-59,0.000000e+00
80489,2019,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,50-59,6.761415e-04

Año: 2019, Edad: 60-69

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2019,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,60-69,2.379294e+00
26,2019,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,60-69,1.410445e-01
27,2019,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,60-69,0.000000e+00
28,2019,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,60-69,0.000000e+00
29,2019,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,60-69,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2019,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,60-69,3.791663e-03
80486,2019,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,60-69,6.337278e-09
80487,2019,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,60-69,2.105928e-01
80488,2019,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,60-69,0.000000e+00
80489,2019,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,60-69,8.100775e-04

Año: 2019, Edad: 70+

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2019,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,70+,1.627481e+00
26,2019,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,70+,5.493945e-02
27,2019,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,70+,0.000000e+00
28,2019,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,70+,0.000000e+00
29,2019,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,70+,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2019,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,70+,3.883446e-03
80486,2019,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,70+,2.716024e-09
80487,2019,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,70+,1.224369e-01
80488,2019,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,70+,0.000000e+00
80489,2019,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,70+,6.181733e-04

Año: 2020, Edad: 0-4

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2020,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,0-4,9.884023e+00
26,2020,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,0-4,1.602859e+00
27,2020,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,0-4,0.000000e+00
28,2020,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,0-4,0.000000e+00
29,2020,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,0-4,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2020,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,0-4,5.032647e-01
80486,2020,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,0-4,1.129232e-08
80487,2020,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,0-4,5.756562e-01
80488,2020,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,0-4,0.000000e+00
80489,2020,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,0-4,5.881487e-06

Año: 2020, Edad: 5-14

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2020,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,5-14,1.786637e+01
26,2020,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,5-14,4.089711e-01
27,2020,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,5-14,0.000000e+00
28,2020,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,5-14,0.000000e+00
29,2020,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,5-14,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2020,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,5-14,9.604482e-02
80486,2020,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,5-14,1.437829e-07
80487,2020,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,5-14,2.412953e+00
80488,2020,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,5-14,0.000000e+00
80489,2020,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,5-14,1.517839e-04

Año: 2020, Edad: 15-29

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2020,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,15-29,1.871677e+01
26,2020,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,15-29,1.556655e+00
27,2020,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,15-29,0.000000e+00
28,2020,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,15-29,0.000000e+00
29,2020,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,15-29,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2020,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,15-29,1.805855e-02
80486,2020,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,15-29,1.827144e-07
80487,2020,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,15-29,1.842787e+00
80488,2020,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,15-29,0.000000e+00
80489,2020,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,15-29,7.096043e-04

Año: 2020, Edad: 30-49

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2020,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,30-49,1.193806e+01
26,2020,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,30-49,4.973239e-01
27,2020,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,30-49,0.000000e+00
28,2020,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,30-49,0.000000e+00
29,2020,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,30-49,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2020,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,30-49,2.156239e-02
80486,2020,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,30-49,8.487160e-08
80487,2020,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,30-49,1.031968e+00
80488,2020,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,30-49,0.000000e+00
80489,2020,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,30-49,1.992588e-03

Año: 2020, Edad: 50-59

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2020,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,50-59,3.587566e+00
26,2020,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,50-59,1.063104e-01
27,2020,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,50-59,0.000000e+00
28,2020,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,50-59,0.000000e+00
29,2020,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,50-59,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2020,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,50-59,4.099417e-03
80486,2020,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,50-59,9.221694e-09
80487,2020,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,50-59,2.085381e-01
80488,2020,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,50-59,0.000000e+00
80489,2020,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,50-59,6.763340e-04

Año: 2020, Edad: 60-69

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2020,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,60-69,2.339911e+00
26,2020,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,60-69,8.875854e-02
27,2020,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,60-69,0.000000e+00
28,2020,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,60-69,0.000000e+00
29,2020,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,60-69,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2020,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,60-69,4.023843e-03
80486,2020,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,60-69,6.316672e-09
80487,2020,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,60-69,2.011326e-01
80488,2020,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,60-69,0.000000e+00
80489,2020,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,60-69,7.838223e-04

Año: 2020, Edad: 70+

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2020,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,70+,1.605215e+00
26,2020,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,70+,3.600502e-02
27,2020,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,70+,0.000000e+00
28,2020,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,70+,0.000000e+00
29,2020,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,70+,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2020,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,70+,4.570528e-03
80486,2020,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,70+,2.858994e-09
80487,2020,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,70+,1.224943e-01
80488,2020,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,70+,0.000000e+00
80489,2020,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,70+,6.271046e-04

Año: 2021, Edad: 0-4

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2021,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,0-4,5.146138e+00
26,2021,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,0-4,1.477648e+00
27,2021,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,0-4,0.000000e+00
28,2021,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,0-4,0.000000e+00
29,2021,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,0-4,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2021,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,0-4,4.991691e-01
80486,2021,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,0-4,1.128154e-08
80487,2021,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,0-4,5.545321e-01
80488,2021,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,0-4,0.000000e+00
80489,2021,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,0-4,5.750014e-06

Año: 2021, Edad: 5-14

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2021,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,5-14,1.757520e+01
26,2021,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,5-14,3.411725e-01
27,2021,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,5-14,0.000000e+00
28,2021,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,5-14,0.000000e+00
29,2021,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,5-14,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2021,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,5-14,1.189389e-01
80486,2021,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,5-14,1.456632e-07
80487,2021,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,5-14,2.338443e+00
80488,2021,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,5-14,0.000000e+00
80489,2021,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,5-14,1.516312e-04

Año: 2021, Edad: 15-29

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2021,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,15-29,1.868991e+01
26,2021,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,15-29,1.292359e+00
27,2021,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,15-29,0.000000e+00
28,2021,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,15-29,0.000000e+00
29,2021,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,15-29,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2021,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,15-29,1.789145e-02
80486,2021,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,15-29,1.862777e-07
80487,2021,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,15-29,1.809425e+00
80488,2021,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,15-29,0.000000e+00
80489,2021,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,15-29,7.071564e-04

Año: 2021, Edad: 30-49

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2021,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,30-49,1.212874e+01
26,2021,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,30-49,4.673768e-01
27,2021,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,30-49,0.000000e+00
28,2021,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,30-49,0.000000e+00
29,2021,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,30-49,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2021,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,30-49,2.687115e-02
80486,2021,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,30-49,8.525231e-08
80487,2021,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,30-49,1.004638e+00
80488,2021,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,30-49,0.000000e+00
80489,2021,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,30-49,2.007711e-03

Año: 2021, Edad: 50-59

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2021,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,50-59,3.667383e+00
26,2021,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,50-59,8.122440e-02
27,2021,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,50-59,0.000000e+00
28,2021,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,50-59,0.000000e+00
29,2021,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,50-59,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2021,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,50-59,4.785489e-03
80486,2021,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,50-59,9.674958e-09
80487,2021,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,50-59,2.081024e-01
80488,2021,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,50-59,0.000000e+00
80489,2021,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,50-59,6.904799e-04

Año: 2021, Edad: 60-69

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2021,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,60-69,2.308833e+00
26,2021,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,60-69,7.282492e-02
27,2021,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,60-69,0.000000e+00
28,2021,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,60-69,0.000000e+00
29,2021,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,60-69,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2021,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,60-69,4.004922e-03
80486,2021,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,60-69,6.249762e-09
80487,2021,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,60-69,1.905550e-01
80488,2021,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,60-69,0.000000e+00
80489,2021,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,60-69,7.598117e-04

Año: 2021, Edad: 70+

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
25,2021,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,70+,1.558973e+00
26,2021,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,70+,2.833502e-02
27,2021,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,70+,0.000000e+00
28,2021,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,70+,0.000000e+00
29,2021,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,70+,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
80485,2021,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,70+,4.103489e-03
80486,2021,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,70+,2.996110e-09
80487,2021,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,70+,1.227859e-01
80488,2021,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,70+,0.000000e+00
80489,2021,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,70+,6.369406e-04

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,DALYs
0,2000,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,0-4,3.660181e+01
1,2000,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,0-4,1.237099e+01
2,2000,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,0-4,0.000000e+00
3,2000,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,0-4,0.000000e+00
4,2000,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,0-4,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
310795,2021,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,70+,4.103489e-03
310796,2021,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,70+,2.996110e-09
310797,2021,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,70+,1.227859e-01
310798,2021,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,70+,0.000000e+00
310799,2021,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,70+,6.369406e-04

### Adición de población tratada por edad y sexo
Estos datos se encuentran en la hoja de datos por país. Se hará un melt por cada una de estas filas y se adicionaran de acuerdo con sexo y edad.

In [5]:
# Extracción de filas superiores.
population_dfs = {}
for año in años:
    file = file_paths[año]
    poblacion_por_edad = {}

    # PASO 1: Cargar TODAS las edades
    for edad in edades:
        print(f"Año: {año}, Edad: {edad}")
        df = pd.read_excel(
            file,
            sheet_name=edad,
            header=None
        )

        # Extraer países
        paises = df.iloc[6, 7:].values
        
        # Extraer poblaciones
        poblacion_males = df.iloc[227, 7:].values if len(df) > 227 else [np.nan] * len(paises)
        poblacion_females = df.iloc[445, 7:].values if len(df) > 445 else [np.nan] * len(paises)

        # Limpiar valores (convertir a número)
        def clean_number(val):
            if pd.isna(val):
                return np.nan
            if isinstance(val, str):
                val = val.replace(',', '').replace(' ', '')
            try:
                return float(val)
            except:
                return np.nan

        poblacion_males = [clean_number(x) for x in poblacion_males]
        poblacion_females = [clean_number(x) for x in poblacion_females]

        # Crear DataFrame temporal
        df_temp = pd.DataFrame({
            'pais': paises,
            f'males_{edad}': poblacion_males,
            f'females_{edad}': poblacion_females
        })
        
        poblacion_por_edad[edad] = df_temp

    # PASO 2: Combinar todas las edades para este año
    # Empezar con la primera edad
    primera_edad = list(poblacion_por_edad.keys())[0]
    df_anual = poblacion_por_edad[primera_edad].copy()
    
    # Hacer merge con las demás edades
    for edad in list(poblacion_por_edad.keys())[1:]:
        df_anual = pd.merge(
            df_anual,
            poblacion_por_edad[edad],
            on='pais',
            how='outer'
        )
    
    # Agregar columna de año
    df_anual['año'] = año
    
    # Guardar
    population_dfs[año] = df_anual
    print(f"  → DataFrame {año}: {df_anual.shape}")

# PASO 3: Concatenar todos los años
df_poblacion_ancho = pd.concat(population_dfs.values(), ignore_index=True)

# PASO 4: Hacer melt
columnas_poblacion = [col for col in df_poblacion_ancho.columns if col not in ['pais', 'año']]

df_poblacion_largo = pd.melt(
    df_poblacion_ancho,
    id_vars=['pais', 'año'],
    value_vars=columnas_poblacion,
    var_name='variable',
    value_name='poblacion_miles'
)

# PASO 5: Extraer sexo y edad CORRECTAMENTE
def extract_sexo_edad(var_name):
    # El formato es: 'males_0-4' o 'females_70+'
    partes = var_name.split('_')
    sexo = 'Males' if partes[0] == 'males' else 'Females'
    edad = partes[1]  # La segunda parte es la edad
    return sexo, edad

df_poblacion_largo[['sexo', 'edad']] = pd.DataFrame(
    df_poblacion_largo['variable'].apply(extract_sexo_edad).tolist(),
    index=df_poblacion_largo.index
)

# PASO 6: ELIMINAR DUPLICADOS (esta es la clave)
print(f"\nAntes de eliminar duplicados: {df_poblacion_largo.shape}")
df_poblacion_largo = df_poblacion_largo.drop_duplicates(
    subset=['año', 'pais', 'sexo', 'edad']
)
print(f"Después de eliminar duplicados: {df_poblacion_largo.shape}")

# Limpiar
df_poblacion_largo = df_poblacion_largo.drop(columns=['variable'])
df_poblacion_largo = df_poblacion_largo[['año', 'pais', 'sexo', 'edad', 'poblacion_miles']]
df_poblacion_largo = df_poblacion_largo.sort_values(['año', 'pais', 'sexo', 'edad']).reset_index(drop=True)

# Verificar que no hay duplicados
print("\nVerificación de duplicados:")
print(df_poblacion_largo.duplicated(subset=['año', 'pais', 'sexo', 'edad']).sum())

display(df_poblacion_largo.head(10))

df_poblacion_largo.to_csv('data_clean/poblacion_tidy.csv', index=False)

Año: 2000, Edad: 0-4
Año: 2000, Edad: 5-14
Año: 2000, Edad: 15-29
Año: 2000, Edad: 30-49
Año: 2000, Edad: 50-59
Año: 2000, Edad: 60-69
Año: 2000, Edad: 70+
  → DataFrame 2000: (185, 16)
Año: 2010, Edad: 0-4
Año: 2010, Edad: 5-14
Año: 2010, Edad: 15-29
Año: 2010, Edad: 30-49
Año: 2010, Edad: 50-59
Año: 2010, Edad: 60-69
Año: 2010, Edad: 70+
  → DataFrame 2010: (185, 16)
Año: 2015, Edad: 0-4
Año: 2015, Edad: 5-14
Año: 2015, Edad: 15-29
Año: 2015, Edad: 30-49
Año: 2015, Edad: 50-59
Año: 2015, Edad: 60-69
Año: 2015, Edad: 70+
  → DataFrame 2015: (185, 16)
Año: 2019, Edad: 0-4
Año: 2019, Edad: 5-14
Año: 2019, Edad: 15-29
Año: 2019, Edad: 30-49
Año: 2019, Edad: 50-59
Año: 2019, Edad: 60-69
Año: 2019, Edad: 70+
  → DataFrame 2019: (185, 16)
Año: 2020, Edad: 0-4
Año: 2020, Edad: 5-14
Año: 2020, Edad: 15-29
Año: 2020, Edad: 30-49
Año: 2020, Edad: 50-59
Año: 2020, Edad: 60-69
Año: 2020, Edad: 70+
  → DataFrame 2020: (185, 16)
Año: 2021, Edad: 0-4
Año: 2021, Edad: 5-14
Año: 2021, Edad: 15-29
Año: 2021, Edad: 30-49
Año: 2021, Edad: 50-59
Año: 2021, Edad: 60-69
Año: 2021, Edad: 70+
  → DataFrame 2021: (185, 16)

Antes de eliminar duplicados: (15540, 6)
Después de eliminar duplicados: (15540, 6)

Verificación de duplicados:
0

    año         pais     sexo   edad  poblacion_miles
0  2000  Afghanistan  Females    0-4         2048.693
1  2000  Afghanistan  Females  15-29         2532.004
2  2000  Afghanistan  Females  30-49         1721.442
3  2000  Afghanistan  Females   5-14         2871.563
4  2000  Afghanistan  Females  50-59          462.311
5  2000  Afghanistan  Females  60-69          264.308
6  2000  Afghanistan  Females    70+          135.364
7  2000  Afghanistan    Males    0-4         2152.578
8  2000  Afghanistan    Males  15-29         2607.001
9  2000  Afghanistan    Males  30-49         1581.735

### Remodelación de variables socioeconómicas
Dado que para estas variables se tienen conjuntos de datos para hombres y mujeres, se clasificará cada índice de acuerdo con la variable de sexo y se hará un merge de topdos estos datos al conjunto principal.

##### Merge de todas los conjuntos de datos de relacionados con índice de desarrollo humano.

In [6]:
# Se hará un loop para ello. Sin embargo, conviene hacer un merge de todo dado que comparten las variables: "Country",	"Continent",	"ISO_Code",	"Level", "GDLCODE",	"Region", "Year"
columnas_merge = ['Country', 'Continent', 'ISO_Code', 'Level', 'GDLCODE', 'Region', 'Year']
fem = []
masc = []

# Loop para desarrollo humano.
dataframes_desarrollo = {}

for key, path in development_paths.items():
    print(f"Dataframe: {key}")
    df = pd.read_csv(path, encoding='latin-1')

    # Agregamos una columna adicional de "sexo" para clasificar cada dataframe de acuerdo con el sexo. 
    # Clasificar por sexo basado en el nombre de la llave
    if key.endswith('_fem') or 'women' in key.lower():
        df['sexo'] = 'Females'
        fem.append(key)
    elif key.endswith('_masc') or 'men' in key.lower():
        df['sexo'] = 'Males'
        masc.append(key)

    dataframes_desarrollo[key] = df

# Tomamos cualquier de los DataFrames (Todos tienen la misma estructura)
df_hdi_base = dataframes_desarrollo['hdi_masc'].copy()

for key, df in dataframes_desarrollo.items():
    if key != 'hdi_masc':  # Evitar merge consigo mismo
        print(f"Merging: {key}")
        df_hdi_base = pd.merge(
            df_hdi_base,
            df,
            on=columnas_merge + ['sexo'],  # 
            how='outer',  # outer para conservar todas las combinaciones
            suffixes=('', f'_{key}')  # Para evitar columnas duplicadas
        )

df_hdi_base = df_hdi_base.drop(columns = ['Continent', 'Level', 'GDLCODE', 'Region'])
df_hdi_base = df_hdi_base.rename(columns={'Country': 'pais', 'ISO_Code': 'codigo_pais', 'Year': 'año'})
display(df_hdi_base)
print(df_hdi_base['sexo'].value_counts())

Dataframe: hdi_masc
Dataframe: hdi_fem
Dataframe: educacion_masc
Dataframe: educacion_fem
Dataframe: salud_masc
Dataframe: salud_fem
Dataframe: ingresos_masc
Dataframe: ingresos_fem
Dataframe: expectancy_masc
Dataframe: expectancy_fem
Merging: hdi_fem
Merging: educacion_masc
Merging: educacion_fem
Merging: salud_masc
Merging: salud_fem
Merging: ingresos_masc
Merging: ingresos_fem
Merging: expectancy_masc
Merging: expectancy_fem

,pais,codigo_pais,año,shdim,sexo,shdif,edindexm,edindexf,healthindexm,healthindexf,incindexm,incindexf,lifexpm,lifexpf
0,Afghanistan,AFG,2000,NaN,Females,NaN,NaN,0.119,NaN,0.529,NaN,NaN,NaN,56.86
1,Afghanistan,AFG,2000,NaN,Males,NaN,0.283,NaN,0.558,NaN,NaN,NaN,53.76,NaN
2,Afghanistan,AFG,2010,NaN,Females,0.353,NaN,0.212,NaN,0.614,NaN,0.339,NaN,62.41
3,Afghanistan,AFG,2010,0.517,Males,NaN,0.416,NaN,0.643,NaN,0.516,NaN,59.28,NaN
4,Afghanistan,AFG,2015,NaN,Females,0.375,NaN,0.248,NaN,0.647,NaN,0.329,NaN,64.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2051,Zimbabwe,ZWE,2019,0.580,Males,NaN,0.631,NaN,0.633,NaN,0.489,NaN,58.64,NaN
2052,Zimbabwe,ZWE,2020,NaN,Females,0.535,NaN,0.570,NaN,0.636,NaN,0.423,NaN,63.86
2053,Zimbabwe,ZWE,2020,0.572,Males,NaN,0.636,NaN,0.625,NaN,0.471,NaN,58.13,NaN
2054,Zimbabwe,ZWE,2021,NaN,Females,0.538,NaN,0.570,NaN,0.608,NaN,0.450,NaN,62.05
2055,Zimbabwe,ZWE,2021,0.560,Males,NaN,0.636,NaN,0.596,NaN,0.463,NaN,56.23,NaN

sexo
Females    1028
Males      1028
Name: count, dtype: int64

#### Variables unificadas por sexo.

In [7]:
# Índex para cada variable - VERSIÓN SIMPLE
mapeo_indices = {
    'hdi': ['shdim', 'shdif'],
    'indice_educacion': ['edindexm', 'edindexf'],
    'indice_salud': ['healthindexm', 'healthindexf'],
    'indice_ingresos': ['incindexm', 'incindexf'],
    'esperanza_vida': ['lifexpm', 'lifexpf']
}

for nombre_base, (col_masc, col_fem) in mapeo_indices.items():
    print(f"Creando {nombre_base} desde {col_masc} y {col_fem}")
    
    # Verificar que las columnas existen DIRECTAMENTE (sin búsqueda compleja)
    if col_masc in df_hdi_base.columns and col_fem in df_hdi_base.columns:
        # Crear columna unificada con np.where
        df_hdi_base[nombre_base] = np.where(
            df_hdi_base['sexo'] == 'Males',
            df_hdi_base[col_masc],
            df_hdi_base[col_fem]
        )
        print(f"{nombre_base} creada")

# Mostrar resultado
print(df_hdi_base.columns.tolist())

df_hdi_base = df_hdi_base.drop(columns = ['shdif', 'shdim', 'edindexm', 'edindexf', 'healthindexm', 'healthindexf', 'incindexm', 'incindexf', 'lifexpm', 'lifexpf'])
display(df_hdi_base)

Creando hdi desde shdim y shdif
hdi creada
Creando indice_educacion desde edindexm y edindexf
indice_educacion creada
Creando indice_salud desde healthindexm y healthindexf
indice_salud creada
Creando indice_ingresos desde incindexm y incindexf
indice_ingresos creada
Creando esperanza_vida desde lifexpm y lifexpf
esperanza_vida creada
['pais', 'codigo_pais', 'año', 'shdim', 'sexo', 'shdif', 'edindexm', 'edindexf', 'healthindexm', 'healthindexf', 'incindexm', 'incindexf', 'lifexpm', 'lifexpf', 'hdi', 'indice_educacion', 'indice_salud', 'indice_ingresos', 'esperanza_vida']

,pais,codigo_pais,año,sexo,hdi,indice_educacion,indice_salud,indice_ingresos,esperanza_vida
0,Afghanistan,AFG,2000,Females,NaN,0.119,0.529,NaN,56.86
1,Afghanistan,AFG,2000,Males,NaN,0.283,0.558,NaN,53.76
2,Afghanistan,AFG,2010,Females,0.353,0.212,0.614,0.339,62.41
3,Afghanistan,AFG,2010,Males,0.517,0.416,0.643,0.516,59.28
4,Afghanistan,AFG,2015,Females,0.375,0.248,0.647,0.329,64.58
...,...,...,...,...,...,...,...,...,...
2051,Zimbabwe,ZWE,2019,Males,0.580,0.631,0.633,0.489,58.64
2052,Zimbabwe,ZWE,2020,Females,0.535,0.570,0.636,0.423,63.86
2053,Zimbabwe,ZWE,2020,Males,0.572,0.636,0.625,0.471,58.13
2054,Zimbabwe,ZWE,2021,Females,0.538,0.570,0.608,0.450,62.05
2055,Zimbabwe,ZWE,2021,Males,0.560,0.636,0.596,0.463,56.23

### Adición de variables socioecocómicas y climáticas
Las hojas para estas variables se modificaron manualmente para poder realizar un merge de acuerdo con los nombres ya estandarizados para las variables.

In [8]:
# Definimos el DataFrame unificado.
df_unificado = pd.read_csv('data_clean/DALYs_clean_unificado.csv')  # Ya está cargado arriba

# Definimos variables que nos funcionarán.
col_order = ['año', 'pais', 'codigo_pais', 'codigo_ghe', 'categoria_principal', 
             'categoria_nivel1', 'categoria_nivel2', 'causa', 'sexo', 'edad', 
             'DALYs', 'intervenciones_NTDs', 'coeficiente_gini', 'GDP per capita', 
             'hdi', 'indice_educacion', 'indice_salud', 'indice_ingresos', 'esperanza_vida',
             'poblacion_miles','co2_anual', 'tot_precip', 'surface_temp', 'rel_humidity']

# Definimos las columnas que nos interesan de cada uno

# Variables socioeconómicas
columnas_gini = ['pais', 'año', 'coeficiente_gini']
columnas_GDP = ['pais', 'codigo_pais', 'año', 'GDP per capita']
columnas_hdi = ['pais', 'codigo_pais', 'sexo', 'año', 'hdi', 'indice_educacion', 'indice_salud', 'indice_ingresos', 'esperanza_vida']
columnas_poblacion = ['año', 'codigo_pais', 'sexo', 'edad', 'poblacion_miles']

# Variables ambientales
columnas_precip = ['pais', 'codigo_pais', 'año', 'tot_precip']
columnas_humid = ['pais', 'codigo_pais', 'año', 'rel_humidity']
columnas_temp = ['pais', 'codigo_pais', 'año', 'surface_temp']
columnas_emisiones = ['pais', 'codigo_pais', 'año', 'co2_anual']


# Merge de los conjuntos de datos que nos interesan.

df_unificado = pd.merge(df_unificado,
                        df_interNTD,
                        on=['pais', 'codigo_pais', 'año'],
                        how='left'
)

df_unificado = pd.merge(df_unificado,
                        df_gini[columnas_gini],
                        on=['pais', 'año'],
                        how='left'
)

df_unificado = pd.merge(df_unificado,
                        df_GDP[columnas_GDP],
                        on=['pais', 'codigo_pais', 'año'],
                        how='left'
)

df_unificado = pd.merge(df_unificado,
                        df_hdi_base[columnas_hdi],
                        on=['pais', 'codigo_pais', 'año', 'sexo'],
                        how='left'
)

# Asegurarnos que df_poblacion_largo tiene código_pais
if 'codigo_pais' not in df_poblacion_largo.columns:
    df_poblacion_largo['codigo_pais'] = df_poblacion_largo['pais'].map(codigos_paises)

df_unificado = pd.merge(df_unificado,
                        df_poblacion_largo[columnas_poblacion],
                        on=['año', 'codigo_pais', 'sexo', 'edad'],
                        how='left'
)

df_unificado = pd.merge(df_unificado,
                        df_precipitacion[columnas_precip],
                        on=['pais', 'codigo_pais', 'año'],
                        how='left'
)

df_unificado = pd.merge(df_unificado,
                        df_humedad[columnas_humid],
                        on=['pais', 'codigo_pais', 'año'],
                        how='left'
)

df_unificado = pd.merge(df_unificado,
                        df_temperatura[columnas_temp],
                        on=['pais', 'codigo_pais', 'año'],
                        how='left'
)

df_unificado = pd.merge(df_unificado,
                        df_emisiones[columnas_emisiones],
                        on=['pais', 'codigo_pais', 'año'],
                        how='left'
)

df_unificado = df_unificado[col_order]

df_unificado.to_csv('data_clean/DALYs_clean_unificado.csv', index=False)
display(df_unificado)

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,...,hdi,indice_educacion,indice_salud,indice_ingresos,esperanza_vida,poblacion_miles,co2_anual,tot_precip,surface_temp,rel_humidity
0,2000,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,0-4,...,NaN,0.283,0.558,NaN,53.76,2152.578,511.1,0.009,9.687,40.39
1,2000,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,0-4,...,NaN,0.283,0.558,NaN,53.76,2152.578,511.1,0.009,9.687,40.39
2,2000,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,0-4,...,NaN,0.283,0.558,NaN,53.76,2152.578,511.1,0.009,9.687,40.39
3,2000,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,0-4,...,NaN,0.283,0.558,NaN,53.76,2152.578,511.1,0.009,9.687,40.39
4,2000,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,0-4,...,NaN,0.283,0.558,NaN,53.76,2152.578,511.1,0.009,9.687,40.39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310795,2021,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,70+,...,0.538,0.570,0.608,0.45,62.05,193.152,26239.0,0.026,21.090,57.65
310796,2021,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,70+,...,0.538,0.570,0.608,0.45,62.05,193.152,26239.0,0.026,21.090,57.65
310797,2021,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,70+,...,0.538,0.570,0.608,0.45,62.05,193.152,26239.0,0.026,21.090,57.65
310798,2021,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,70+,...,0.538,0.570,0.608,0.45,62.05,193.152,26239.0,0.026,21.090,57.65
310799,2021,Zimbabwe,ZWE,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,70+,...,0.538,0.570,0.608,0.45,62.05,193.152,26239.0,0.026,21.090,57.65

## E. Limpieza de Datos

In [15]:
display(df_unificado)

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,...,hdi,indice_educacion,indice_salud,indice_ingresos,esperanza_vida,poblacion_miles,co2_anual,tot_precip,surface_temp,rel_humidity
0,2000,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,0-4,...,NaN,0.283,0.558,NaN,53.76,2152.578,511.1,0.009,9.687,40.39
1,2000,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,0-4,...,NaN,0.283,0.558,NaN,53.76,2152.578,511.1,0.009,9.687,40.39
2,2000,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,0-4,...,NaN,0.283,0.558,NaN,53.76,2152.578,511.1,0.009,9.687,40.39
3,2000,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,0-4,...,NaN,0.283,0.558,NaN,53.76,2152.578,511.1,0.009,9.687,40.39
4,2000,Afghanistan,AFG,260.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,e.Leishmaniasis,Males,0-4,...,NaN,0.283,0.558,NaN,53.76,2152.578,511.1,0.009,9.687,40.39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295255,2021,Zimbabwe,ZWE,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,70+,...,0.538,0.570,0.608,0.45,62.05,193.152,26239.0,0.026,21.090,57.65
295256,2021,Zimbabwe,ZWE,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,70+,...,0.538,0.570,0.608,0.45,62.05,193.152,26239.0,0.026,21.090,57.65
295257,2021,Zimbabwe,ZWE,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,70+,...,0.538,0.570,0.608,0.45,62.05,193.152,26239.0,0.026,21.090,57.65
295258,2021,Zimbabwe,ZWE,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,70+,...,0.538,0.570,0.608,0.45,62.05,193.152,26239.0,0.026,21.090,57.65
295259,2021,Zimbabwe,ZWE,370.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,12.Other infectious diseases,Other infectious diseases,Females,70+,...,0.538,0.570,0.608,0.45,62.05,193.152,26239.0,0.026,21.090,57.65

In [9]:
# Leemos los datos después de haber sido procesados.
df = pd.read_csv('data_clean/DALYs_clean_unificado.csv')
df.dtypes

año                      int64
pais                    object
codigo_pais             object
codigo_ghe             float64
categoria_principal     object
categoria_nivel1        object
categoria_nivel2        object
causa                   object
sexo                    object
edad                    object
DALYs                  float64
intervenciones_NTDs    float64
coeficiente_gini       float64
GDP per capita         float64
hdi                    float64
indice_educacion       float64
indice_salud           float64
indice_ingresos        float64
esperanza_vida         float64
poblacion_miles        float64
co2_anual              float64
tot_precip             float64
surface_temp           float64
rel_humidity           float64
dtype: object

In [10]:
# Cambio de tipo de variables.
df.columns = ['año', 'pais', 'codigo_pais', 'codigo_ghe', 'categoria_principal', 'categoria_nivel1', 'categoria_nivel2', 'causa',
             'sexo', 'edad', 'DALYs', 'intervenciones_NTDs', 'coeficiente_gini', 'GDP per capita', 'hdi', 'indice_educacion', 
             'indice_salud', 'indice_ingresos', 'esperanza_vida', 'poblacion_miles', 'co2_anual',
             'tot_precip', 'surface_temp', 'rel_humidity']

# Cambio de tipo de variables
df['año'] = df['año'].astype(int)

# Columnas de tipo categórico
columnas_categoricas = ['pais', 'codigo_pais', 'codigo_ghe', 'categoria_principal', 'categoria_nivel1', 
                       'categoria_nivel2', 'causa', 'sexo', 'edad']

# Loop: por cada columna en el vector columnas categóricas, cambiar el tipo a categórico
for col in columnas_categoricas:
    df[col] = df[col].astype('category')

# Float para las variables numéricas.
columnas_float = ['DALYs', 'intervenciones_NTDs', 'coeficiente_gini', 'GDP per capita', 
                  'hdi', 'indice_educacion', 'indice_salud', 'indice_ingresos', 'esperanza_vida',
                  'co2_anual', 'poblacion_miles','tot_precip', 'surface_temp', 'rel_humidity']

for col in columnas_float:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Check the new dtypes
print(df.dtypes)

año                       int64
pais                   category
codigo_pais            category
codigo_ghe             category
categoria_principal    category
categoria_nivel1       category
categoria_nivel2       category
causa                  category
sexo                   category
edad                   category
DALYs                   float64
intervenciones_NTDs     float64
coeficiente_gini        float64
GDP per capita          float64
hdi                     float64
indice_educacion        float64
indice_salud            float64
indice_ingresos         float64
esperanza_vida          float64
poblacion_miles         float64
co2_anual               float64
tot_precip              float64
surface_temp            float64
rel_humidity            float64
dtype: object

In [11]:
df.isna().sum()

año                         0
pais                        0
codigo_pais                 0
codigo_ghe                  0
categoria_principal         0
categoria_nivel1            0
categoria_nivel2            0
causa                   31080
sexo                        0
edad                        0
DALYs                       0
intervenciones_NTDs     81200
coeficiente_gini       176400
GDP per capita          40880
hdi                     86240
indice_educacion        70840
indice_salud            72800
indice_ingresos         77840
esperanza_vida          72800
poblacion_miles             0
co2_anual               52080
tot_precip              52080
surface_temp            52080
rel_humidity            52080
dtype: int64

In [12]:
df.isna().sum(axis=1).value_counts().sort_index()

0      65016
1     132972
2      23800
3      13944
4       4200
5       7868
6       9156
7       3192
8        252
9       6048
10     13272
11      2408
12     25816
13      2856
Name: count, dtype: int64

In [13]:
df[  df.isna().sum(axis=1)>=5  ]

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,...,hdi,indice_educacion,indice_salud,indice_ingresos,esperanza_vida,poblacion_miles,co2_anual,tot_precip,surface_temp,rel_humidity
120,2000,Angola,AGO,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,0-4,...,NaN,NaN,NaN,NaN,NaN,1491.562,4901.0,0.034,22.21,64.06
121,2000,Angola,AGO,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,0-4,...,NaN,NaN,NaN,NaN,NaN,1491.562,4901.0,0.034,22.21,64.06
122,2000,Angola,AGO,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,0-4,...,NaN,NaN,NaN,NaN,NaN,1491.562,4901.0,0.034,22.21,64.06
123,2000,Angola,AGO,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,0-4,...,NaN,NaN,NaN,NaN,NaN,1491.562,4901.0,0.034,22.21,64.06
124,2000,Angola,AGO,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,0-4,...,NaN,NaN,NaN,NaN,NaN,1491.562,4901.0,0.034,22.21,64.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310675,2021,Viet Nam,VNM,340.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,a.Ascariasis,Females,70+,...,NaN,NaN,NaN,NaN,NaN,3011.778,NaN,NaN,NaN,NaN
310676,2021,Viet Nam,VNM,350.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,b.Trichuriasis,Females,70+,...,NaN,NaN,NaN,NaN,NaN,3011.778,NaN,NaN,NaN,NaN
310677,2021,Viet Nam,VNM,360.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,c.Hookworm disease,Females,70+,...,NaN,NaN,NaN,NaN,NaN,3011.778,NaN,NaN,NaN,NaN
310678,2021,Viet Nam,VNM,362.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,10.Intestinal nematode infections,d.Food-borne trematodes,Females,70+,...,NaN,NaN,NaN,NaN,NaN,3011.778,NaN,NaN,NaN,NaN
310679,2021,Viet Nam,VNM,365.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,11.Leprosy,Leprosy,Females,70+,...,NaN,NaN,NaN,NaN,NaN,3011.778,NaN,NaN,NaN,NaN

In [14]:
df[ df.duplicated(keep=False) ]

Empty DataFrame
Columns: [año, pais, codigo_pais, codigo_ghe, categoria_principal, categoria_nivel1, categoria_nivel2, causa, sexo, edad, DALYs, intervenciones_NTDs, coeficiente_gini, GDP per capita, hdi, indice_educacion, indice_salud, indice_ingresos, esperanza_vida, poblacion_miles, co2_anual, tot_precip, surface_temp, rel_humidity]
Index: []

[0 rows x 24 columns]

In [15]:
df.isna().sum() / df.shape[0] * 100

año                     0.000000
pais                    0.000000
codigo_pais             0.000000
codigo_ghe              0.000000
categoria_principal     0.000000
categoria_nivel1        0.000000
categoria_nivel2        0.000000
causa                  10.000000
sexo                    0.000000
edad                    0.000000
DALYs                   0.000000
intervenciones_NTDs    26.126126
coeficiente_gini       56.756757
GDP per capita         13.153153
hdi                    27.747748
indice_educacion       22.792793
indice_salud           23.423423
indice_ingresos        25.045045
esperanza_vida         23.423423
poblacion_miles         0.000000
co2_anual              16.756757
tot_precip             16.756757
surface_temp           16.756757
rel_humidity           16.756757
dtype: float64

A raíz de la falta de datos para algunas variables se optará por eliminar el índice Gini y en el caso de 'intervenciones_NTD', los índices de desarrollo humano y variables climáticas se optará por eliminar sólo los países que reducir la cantidad de NaN.

### Limpieza de variables

In [16]:
df.columns # Revisamos nuestras variables.

Index(['año', 'pais', 'codigo_pais', 'codigo_ghe', 'categoria_principal',
       'categoria_nivel1', 'categoria_nivel2', 'causa', 'sexo', 'edad',
       'DALYs', 'intervenciones_NTDs', 'coeficiente_gini', 'GDP per capita',
       'hdi', 'indice_educacion', 'indice_salud', 'indice_ingresos',
       'esperanza_vida', 'poblacion_miles', 'co2_anual', 'tot_precip',
       'surface_temp', 'rel_humidity'],
      dtype='object')

In [17]:
# Nos quedamos con todas menos coeficiente gini e intervenciones
col_drop = [ 'coeficiente_gini', 'intervenciones_NTDs' ]
df = df.drop( col_drop, axis=1)
df.head()

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,...,hdi,indice_educacion,indice_salud,indice_ingresos,esperanza_vida,poblacion_miles,co2_anual,tot_precip,surface_temp,rel_humidity
0,2000,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,0-4,...,NaN,0.283,0.558,NaN,53.76,2152.578,511.1,0.009,9.687,40.39
1,2000,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,0-4,...,NaN,0.283,0.558,NaN,53.76,2152.578,511.1,0.009,9.687,40.39
2,2000,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,0-4,...,NaN,0.283,0.558,NaN,53.76,2152.578,511.1,0.009,9.687,40.39
3,2000,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,0-4,...,NaN,0.283,0.558,NaN,53.76,2152.578,511.1,0.009,9.687,40.39
4,2000,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,0-4,...,NaN,0.283,0.558,NaN,53.76,2152.578,511.1,0.009,9.687,40.39

Ahora eliminamos todas aquellas filas que tengan más 6 NaN

In [18]:
# Definimos el número de columnas que se tienen
max_NAN = 4
total_columnas = df.shape[1] # Número de columnas (en este caso 20)

min_valores = total_columnas - max_NAN # Debemos tener mínimo 8 valores no NaN

df = df.dropna(thresh=min_valores, axis=0)

df.isna().sum() / df.shape[0] * 100

año                    0.000000
pais                   0.000000
codigo_pais            0.000000
codigo_ghe             0.000000
categoria_principal    0.000000
categoria_nivel1       0.000000
categoria_nivel2       0.000000
causa                  9.865161
sexo                   0.000000
edad                   0.000000
DALYs                  0.000000
GDP per capita         4.068226
hdi                    7.640890
indice_educacion       1.382966
indice_salud           2.109024
indice_ingresos        4.379394
esperanza_vida         2.109024
poblacion_miles        0.000000
co2_anual              0.622335
tot_precip             0.622335
surface_temp           0.622335
rel_humidity           0.622335
dtype: float64

In [19]:
df.head()

,año,pais,codigo_pais,codigo_ghe,categoria_principal,categoria_nivel1,categoria_nivel2,causa,sexo,edad,...,hdi,indice_educacion,indice_salud,indice_ingresos,esperanza_vida,poblacion_miles,co2_anual,tot_precip,surface_temp,rel_humidity
0,2000,Afghanistan,AFG,210.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,NaN,Males,0-4,...,NaN,0.283,0.558,NaN,53.76,2152.578,511.1,0.009,9.687,40.39
1,2000,Afghanistan,AFG,220.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,a.Malaria,Males,0-4,...,NaN,0.283,0.558,NaN,53.76,2152.578,511.1,0.009,9.687,40.39
2,2000,Afghanistan,AFG,230.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,b.Trypanosomiasis,Males,0-4,...,NaN,0.283,0.558,NaN,53.76,2152.578,511.1,0.009,9.687,40.39
3,2000,Afghanistan,AFG,240.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,c.Chagas disease,Males,0-4,...,NaN,0.283,0.558,NaN,53.76,2152.578,511.1,0.009,9.687,40.39
4,2000,Afghanistan,AFG,250.0,"I.Communicable, maternal, perinatal and nutrit...",A.Infectious and parasitic diseases,9.Parasitic and vector diseases,d.Schistosomiasis,Males,0-4,...,NaN,0.283,0.558,NaN,53.76,2152.578,511.1,0.009,9.687,40.39

También se limpiaran los nombres de las variables y valores.

In [20]:
# !!!! Aplicar sólo una vez !!!!

# Cambio del nombre de columnas a un formato sin espacios, sin acentos

renombrar_columnas = {
    'año': 'ano',
    'pais': 'pais',
    'codigo_pais': 'codigo_pais',
    'codigo_ghe': 'codigo_ghe',
    'categoria_principal': 'categoria_principal',
    'categoria_nivel1': 'categoria_nivel1',
    'categoria_nivel2': 'categoria_nivel2',
    'causa': 'causa',
    'sexo': 'sexo',
    'edad': 'edad',
    'DALYs': 'dalys',
    'coeficiente_gini': 'coeficiente_gini',
    'GDP per capita': 'pib_per_capita',
    'hdi': 'idh',
    'indice_educacion': 'indice_educacion',
    'indice_salud': 'indice_salud',
    'indice_ingresos': 'indice_ingresos',
    'esperanza_vida': 'esperanza_vida',
    'poblacion_miles': 'poblacion_miles',
    'co2_anual': 'co2_anual',
    'tot_precip': 'precipitacion_total',
    'surface_temp': 'temperatura_superficial',
    'rel_humidity': 'humedad_relativa'
}

df = df.rename(columns=renombrar_columnas)
print("\nNombres estandarizados:", df.columns.tolist())

Nombres estandarizados: ['ano', 'pais', 'codigo_pais', 'codigo_ghe', 'categoria_principal', 'categoria_nivel1', 'categoria_nivel2', 'causa', 'sexo', 'edad', 'dalys', 'pib_per_capita', 'idh', 'indice_educacion', 'indice_salud', 'indice_ingresos', 'esperanza_vida', 'poblacion_miles', 'co2_anual', 'precipitacion_total', 'temperatura_superficial', 'humedad_relativa']

# F. Variables Nuevas
Se agregaran variables más explicativas al conjunto de datos. Estas serán: Variable de población absoluta 'poblacion_abs'; Tasa de DALYs por cada 100,000 habitantes 'tasa_dalys_100k'; DALYs por intervención 'dalys_por_intervencion'; Desarollo humano (IDH) vs la carga de la enfermedad 'desarrollo_vs_carga'

In [21]:
# 1. Población absoluta (para cálculos posteriores)
df['poblacion_abs'] = df['poblacion_miles'] * 1000

# 2. Tasa de DALYs por 100,000 habitantes
#    Permite comparar la carga de enfermedad entre países de diferente tamaño poblacional
df['tasa_dalys_100k'] = (df['dalys'] / df['poblacion_abs']) * 100000


# 3. DALYs por intervención (relación carga de enfermedad vs. recursos)
#    Se suma 1 al numerador para evitar división por cero
df['dalys_por_intervencion'] = (df['dalys'] + 1) / df['poblacion_abs']

# 4. Desarrollo humano vs. carga de enfermedad (interacción IDH × tasa)
#    Captura el efecto conjunto del desarrollo y la carga de enfermedad
df['desarrollo_vs_carga'] = df['idh'] * df['tasa_dalys_100k']

print(df.columns.tolist())

['ano', 'pais', 'codigo_pais', 'codigo_ghe', 'categoria_principal', 'categoria_nivel1', 'categoria_nivel2', 'causa', 'sexo', 'edad', 'dalys', 'pib_per_capita', 'idh', 'indice_educacion', 'indice_salud', 'indice_ingresos', 'esperanza_vida', 'poblacion_miles', 'co2_anual', 'precipitacion_total', 'temperatura_superficial', 'humedad_relativa', 'poblacion_abs', 'tasa_dalys_100k', 'dalys_por_intervencion', 'desarrollo_vs_carga']

In [ ]:
df.dtypes

ano                           int64
pais                       category
codigo_pais                category
codigo_ghe                 category
categoria_principal        category
categoria_nivel1           category
categoria_nivel2           category
causa                      category
sexo                       category
edad                       category
dalys                       float64
pib_per_capita              float64
idh                         float64
indice_educacion            float64
indice_salud                float64
indice_ingresos             float64
esperanza_vida              float64
poblacion_miles             float64
co2_anual                   float64
precipitacion_total         float64
temperatura_superficial     float64
humedad_relativa            float64
poblacion_abs               float64
tasa_dalys_100k             float64
dalys_por_intervencion      float64
desarrollo_vs_carga         float64
dtype: object

Guardar datos en pickle y CSV para compartir

In [23]:
# CSV ´para compartir
df.to_csv('data_clean/DALYs_clean_unificado_NEW.csv', index=False)

# Pickle para preservar estructura de datos.
df.to_pickle('data_clean/DALYs_clean_unificado_NEW.pkl')

# G. Perfil de Datos

In [1]:
# Después de cargar tus datos
import pandas as pd
from ydata_profiling import ProfileReport

# Se carga el archivo de datos ya remodelados.
Def_Profile = pd.read_csv('data_clean/DALYs_clean_unificado_NEW.csv')

# VERIFICAR NOMBRES DE COLUMNAS (IMPORTANTE)
print("Nombres de columnas en el DataFrame:")
print(Def_Profile.columns.tolist())

# También se cargarán los datos para cada año.
file_paths = {
    2000: 'data_clean/DALYs_clean_2010.csv',
    2010: 'data_clean/DALYs_clean_2010.csv',
    2015: 'data_clean/DALYs_clean_2015.csv',
    2019: 'data_clean/DALYs_clean_2019.csv',
    2020: 'data_clean/DALYs_clean_2020.csv',
    2021: 'data_clean/DALYs_clean_2021.csv'
}

# Definimos una variable de año para automatizar la generación de los perfiles para esos años.
años = [2000, 2010, 2015, 2019, 2020, 2021]

for año in años:
    file = file_paths[año]
    print(f"Perfil del año: {año}")
    # Cargar archivos
    df = pd.read_csv(file)
    file_profile = f"profiles/Clean_Profiles/{año}_profiles.html"
    prof = ProfileReport(df, title=f"Global {año} DALYs Profile", explorative=True)
    prof.to_file(output_file=file_profile)

# Crear diccionario de metadatos para el profile
metadata = {
    "dataset": {
        "description": "DALYs (Disability-Adjusted Life Years) para Enfermedades Tropicales Desatendidas (NTDs) por país, año, sexo y edad. Datos de la Organización Mundial de la Salud - Global Health Estimates 2021, enriquecidos con indicadores socioeconómicos, demográficos y climáticos.",
        "creator": "Organización Mundial de la Salud (WHO); Global Data Lab (GDL); Our World in Data",
        "url": "https://www.who.int/data/gho/data/themes/mortality-and-global-health-estimates/global-health-estimates-leading-causes-of-dalys/"
    },
    "variables": {
        # --- VARIABLES BASE ---
        "ano": {
            "type": "int64",
            "description": "Año de la estimación (2010, 2015, 2019, 2020, 2021).",
            "source": "Global Health Estimates 2021: Disease burden by Cause, Age, Sex, by Country and by Region, 2000-2021. Geneva, World Health Organization; 2024.",
            "cleaning": "Se extrajo del nombre del archivo original."
        },
        "pais": {
            "type": "category",
            "description": "Nombre del país o territorio.",
            "source": "OMS GHE 2021",
            "cleaning": "Se transformó de formato ancho a largo usando pd.melt()."
        },
        "codigo_pais": {
            "type": "category",
            "description": "Código ISO alfa-3 del país.",
            "source": "Global Health Estimates 2021",
            "cleaning": "Se agregó mediante mapeo del nombre del país."
        },
        "codigo_ghe": {
            "type": "category",
            "description": "Código numérico de la enfermedad según la clasificación de la OMS. Se filtró para incluir solo los códigos correspondientes a Enfermedades Tropicales Desatendidas (NTDs).",
            "source": "Global Health Estimates 2021",
            "cleaning": "Se filtró para conservar solo códigos de NTDs y se convirtió a tipo categórico."
        },
        "categoria_principal": {
            "type": "category",
            "description": "Categoría principal de la enfermedad (nivel superior en jerarquía OMS).",
            "source": "Global Health Estimates 2021",
            "cleaning": "Valores vacíos completados con forward fill (ffill()) y añadido mediante merge con catálogo."
        },
        "categoria_nivel1": {
            "type": "category",
            "description": "Primer nivel de subcategoría de la enfermedad.",
            "source": "Global Health Estimates 2021",
            "cleaning": "Valores vacíos completados con forward fill (ffill()) y añadido mediante merge con catálogo."
        },
        "categoria_nivel2": {
            "type": "category",
            "description": "Segundo nivel de subcategoría de la enfermedad.",
            "source": "Global Health Estimates 2021",
            "cleaning": "Valores vacíos completados con forward fill (ffill()) y añadido mediante merge con catálogo."
        },
        "causa": {
            "type": "category",
            "description": "Nombre específico de la enfermedad o causa. Los valores NaN representan categorías agregadas (no causas específicas) dentro de la jerarquía de la OMS.",
            "source": "Global Health Estimates 2021",
            "cleaning": "Se mantuvieron los NaN para diferenciar entre categorías agregadas y causas específicas."
        },
        "sexo": {
            "type": "category",
            "description": "Sexo de la población afectada ('Males' o 'Females').",
            "source": "Global Health Estimates 2021",
            "cleaning": "Los datos de hombres y mujeres se procesaron por separado y luego se combinaron."
        },
        "edad": {
            "type": "category",
            "description": "Rango de edad de la población afectada (0-4, 5-14, 15-29, 30-49, 50-59, 60-69, 70+).",
            "source": "Global Health Estimates 2021",
            "cleaning": "Se extrajo del nombre de las hojas del Excel original."
        },
        "dalys": {  # Cambiado de "dalys" a "DALYs" (mayúsculas)
            "type": "float64",
            "description": "Años de Vida Ajustados por Discapacidad. Métrica que combina años de vida perdidos por muerte prematura (YLL) y años vividos con discapacidad (YLD).",
            "source": "Global Health Estimates 2021",
            "cleaning": "Se transformó de formato ancho a largo mediante pd.melt()."
        },
        
        # --- VARIABLES DE FUENTES EXTERNAS ---
        "pib_per_capita": {
            "type": "float64",
            "description": "Producto Interno Bruto per cápita ajustado por inflación y paridad de poder adquisitivo (PPP).",
            "source": "Our World in Data, basado en datos del Banco Mundial y la Penn World Table.",
            "cleaning": "Se realizó un merge de tipo 'left' con el dataset principal. Se conservó a pesar de algunos valores NaN."
        },
        
        # --- VARIABLES DE DESARROLLO HUMANO (GDL) ---
        "idh": {
            "type": "float64",
            "description": "Índice de Desarrollo Humano (IDH) subnacional. Una medida resumen del logro promedio en salud, educación e ingresos.",
            "source": "Global Data Lab (GDL), Subnational Human Development Index (SHDI). https://globaldatalab.org. Uso no comercial.",
            "cleaning": "Se unificaron archivos separados por sexo usando np.where y se añadió mediante merge."
        },
        "indice_educacion": {
            "type": "float64",
            "description": "Índice de educación, un componente del IDH subnacional.",
            "source": "Global Data Lab (GDL). https://globaldatalab.org. Uso no comercial.",
            "cleaning": "Creado a partir de 'edindexm' y 'edindexf' usando np.where y añadido mediante merge."
        },
        "indice_salud": {
            "type": "float64",
            "description": "Índice de salud, un componente del IDH subnacional.",
            "source": "Global Data Lab (GDL). https://globaldatalab.org. Uso no comercial.",
            "cleaning": "Creado a partir de 'healthindexm' y 'healthindexf' usando np.where y añadido mediante merge."
        },
        "indice_ingresos": {
            "type": "float64",
            "description": "Índice de ingresos, un componente del IDH subnacional.",
            "source": "Global Data Lab (GDL). https://globaldatalab.org. Uso no comercial.",
            "cleaning": "Creado a partir de 'incindexm' y 'incindexf' usando np.where y añadido mediante merge."
        },
        "esperanza_vida": {
            "type": "float64",
            "description": "Esperanza de vida al nacer, en años (dato utilizado para construir el índice de salud del IDH).",
            "source": "Global Data Lab (GDL). https://globaldatalab.org. Uso no comercial.",
            "cleaning": "Creado a partir de 'lifexpm' y 'lifexpf' usando np.where y añadido mediante merge."
        },
        
        # --- VARIABLES DEMOGRÁFICAS Y AMBIENTALES ---
        "poblacion_miles": {
            "type": "float64",
            "description": "Población total, en miles de personas, para el grupo de sexo y edad específico.",
            "source": "Global Health Estimates 2021",
            "cleaning": "Extraído de filas específicas (227 y 445) de cada hoja Excel, pivotado a formato largo y añadido con merge."
        },
        "co2_anual": {
            "type": "float64",
            "description": "Emisiones anuales totales de CO2, en toneladas.",
            "source": "Global Data Lab (GDL). https://globaldatalab.org. Uso no comercial.",
            "cleaning": "Añadido mediante left merge tras limpieza manual del archivo fuente."
        },
        "precipitacion_total": {
            "type": "float64",
            "description": "Precipitación total anual (lluvia y nieve), en metros.",
            "source": "Global Data Lab (GDL), procesa datos de Copernicus Climate Change Service. https://globaldatalab.org. Uso no comercial.",
            "cleaning": "Añadido mediante left merge tras limpieza manual del archivo fuente."
        },
        "temperatura_superficial": {
            "type": "float64",
            "description": "Temperatura superficial promedio anual, en grados Celsius.",
            "source": "Global Data Lab (GDL), procesa datos de Copernicus Climate Change Service. https://globaldatalab.org. Uso no comercial.",
            "cleaning": "Añadido mediante left merge tras limpieza manual del archivo fuente."
        },
        "humedad_relativa": {
            "type": "float64",
            "description": "Humedad relativa promedio anual, en porcentaje.",
            "source": "Global Data Lab (GDL), procesa datos de Copernicus Climate Change Service. https://globaldatalab.org. Uso no comercial.",
            "cleaning": "Añadido mediante left merge tras limpieza manual del archivo fuente."
        },
        
        # --- VARIABLES DERIVADAS ---
        "poblacion_abs": {
            "type": "float64",
            "description": "Población absoluta calculada a partir de 'poblacion_miles' para facilitar cálculos posteriores.",
            "source": "Derivada de Global Health Estimates 2021.",
            "cleaning": "Creada mediante la operación: poblacion_abs = poblacion_miles × 1000",
            "calculation": "poblacion_abs = poblacion_miles * 1000"
        },
        "tasa_dalys_100k": {
            "type": "float64",
            "description": "Tasa de DALYs por cada 100,000 habitantes. Variable fundamental que permite comparar la carga de la enfermedad entre países o regiones con diferentes tamaños de población.",
            "source": "Derivada de Global Health Estimates 2021.",
            "cleaning": "Calculada como: (DALYs / población_absoluta) × 100,000",
            "calculation": "tasa_dalys_100k = (DALYs / poblacion_abs) × 100000",
            "interpretation": "Valores más altos indican una mayor carga de la enfermedad relativa al tamaño de la población."
        },
        "dalys_por_intervencion": {
            "type": "float64",
            "description": "Relación entre los DALYs y el número de intervenciones contra NTDs. Un valor alto puede indicar baja efectividad de las intervenciones.",
            "source": "Derivada de Global Health Estimates 2021 y WHO GHO.",
            "cleaning": "Calculada como DALYs / (intervenciones_NTDs + 1). Se suma 1 al denominador para evitar división por cero.",
            "calculation": "dalys_por_intervencion = DALYs / (intervenciones_ntds + 1)",
            "interpretation": "Valores altos sugieren baja efectividad relativa de las intervenciones."
        },
        "desarrollo_vs_carga": {
            "type": "float64",
            "description": "Variable de interacción entre el Índice de Desarrollo Humano (IDH) y la tasa de DALYs. Captura el efecto conjunto del nivel de desarrollo y la carga de la enfermedad.",
            "source": "Derivada de Global Data Lab (GDL) y Global Health Estimates 2021.",
            "cleaning": "Calculada como el producto de 'idh' y 'tasa_dalys_100k'.",
            "calculation": "desarrollo_vs_carga = idh × tasa_dalys_100k",
            "interpretation": "Permite identificar si la relación entre desarrollo humano y carga de enfermedad es consistente."
        }
    }
}

# Para el perfil del conjunto de datos.
file_profile = "profiles/Clean_Profiles/Profile_DALYs.html"
print("Perfil de DALYs global")
prof = ProfileReport(
    Def_Profile,
    title="DALYs para Enfermedades Tropicales Desatendidas (2000-2021)",
    dataset=metadata,
    explorative=True
)
prof.to_file(output_file=file_profile)

c:\ProgramData\anaconda3\envs\ydata_profiling\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Nombres de columnas en el DataFrame:
['ano', 'pais', 'codigo_pais', 'codigo_ghe', 'categoria_principal', 'categoria_nivel1', 'categoria_nivel2', 'causa', 'sexo', 'edad', 'dalys', 'pib_per_capita', 'idh', 'indice_educacion', 'indice_salud', 'indice_ingresos', 'esperanza_vida', 'poblacion_miles', 'co2_anual', 'precipitacion_total', 'temperatura_superficial', 'humedad_relativa', 'poblacion_abs', 'tasa_dalys_100k', 'dalys_por_intervencion', 'desarrollo_vs_carga']
Perfil del año: 2000

100%|██████████| 11/11 [00:00<00:00, 145.23it/s]00:00, 19.06it/s, Describe variable: DALYs]
Summarize dataset: 100%|██████████| 24/24 [00:00<00:00, 25.47it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:01<00:00,  1.22s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  3.76it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 284.94it/s]

Perfil del año: 2010

100%|██████████| 11/11 [00:00<00:00, 480.42it/s]00:01,  8.18it/s, Describe variable: DALYs]
Summarize dataset: 100%|██████████| 24/24 [00:00<00:00, 32.43it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:01<00:00,  1.08s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00, 13.22it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 285.17it/s]

Perfil del año: 2015

100%|██████████| 11/11 [00:00<00:00, 458.00it/s]00:01,  8.05it/s, Describe variable: DALYs]
Summarize dataset: 100%|██████████| 24/24 [00:00<00:00, 26.87it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:01<00:00,  1.07s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00, 13.71it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 285.42it/s]

Perfil del año: 2019

100%|██████████| 11/11 [00:00<00:00, 439.81it/s]00:01,  9.90it/s, Describe variable: DALYs]
Summarize dataset: 100%|██████████| 24/24 [00:01<00:00, 16.08it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:01<00:00,  1.21s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00, 13.58it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 250.02it/s]

Perfil del año: 2020

100%|██████████| 11/11 [00:00<00:00, 105.18it/s]00:00, 11.23it/s, Describe variable: DALYs]
Summarize dataset: 100%|██████████| 24/24 [00:02<00:00,  9.30it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:01<00:00,  1.38s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00, 14.85it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 397.11it/s]

Perfil del año: 2021

100%|██████████| 11/11 [00:00<00:00, 261.35it/s]00:00, 21.71it/s, Describe variable: DALYs]
Summarize dataset: 100%|██████████| 24/24 [00:01<00:00, 19.17it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:01<00:00,  1.29s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00, 13.02it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 227.08it/s]

Perfil de DALYs global

100%|██████████| 26/26 [00:01<00:00, 23.10it/s]4<00:03,  2.20it/s, Describe variable: desarrollo_vs_carga]
Summarize dataset: 100%|██████████| 360/360 [00:32<00:00, 10.95it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:02<00:00,  2.52s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  1.28it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 28.20it/s]

## Referencias
[^1]: Global Health Estimates 2021: Disease burden by Cause, Age, Sex, by Country and by Region, 2000-2021. Geneva, World Health Organization; 2024.