# Limpieza de datos-
A raíz de que los datos elegidos para el proyecto tienen problemas de multiíndice y filas con celdas vacías, se realizará una limpieza de datos para poder trabajar con ellos.

In [1]:
# Librerías necesarias
import pandas as pd
import numpy as np

In [2]:
# Definimos el path del archivo .xslsx y los años que nos interesan para el análisis.
archivo = 'data_raw/DALYs/ghe2021_daly_global_new.xlsx'

In [3]:
# Cargamos datos y pandas.
df = pd.read_excel(archivo)
df

     Unnamed: 0 Unnamed: 1                                     Unnamed: 2
0           NaN        NaN   GLOBAL HEALTH ESTIMATES 2021 SUMMARY TABLES:
1           NaN        NaN  GLOBAL DALYs BY CAUSE, AGE AND SEX, 2000-2021
2           NaN        NaN                                            NaN
3           NaN        NaN                                      July 2024
4           NaN        NaN                                            NaN
..          ...        ...                                            ...
199         NaN        NaN             Venezuela (Bolivarian Republic of)
200         NaN        NaN                                       Viet Nam
201         NaN        NaN                                          Yemen
202         NaN        NaN                                         Zambia
203         NaN        NaN                                       Zimbabwe

[204 rows x 3 columns]

Dado que el dataset tiene un multíindice, se usará el método ffill para rellenar las celdas vacías con el valor de la fila anterior. Esto permitirá que cada fila tenga toda la información necesaria para su análisis posterior.

Además, necestimos leer la hoja de excel de los años que nos interesan (2000-2021) y aplicar el método ffill a cada una de ellas para obtener un dataset limpio y listo para su análisis.

In [4]:
# Lectura de hoja "Global 2021"
G2021= pd.read_excel(archivo, sheet_name="Global 2021")
G2021
# Lectura de hoja "Global 2020"
G2020 = pd.read_excel(archivo, sheet_name="Global 2020")
G2020
# Lectura de hoja "Global 2019"
G2019 = pd.read_excel(archivo, sheet_name="Global 2019")
G2019
# Lectura de hoja "Global 2015"
G2015 = pd.read_excel(archivo, sheet_name="Global 2015")
G2015
# Lectura de hoja "Global 2010"
G2010 = pd.read_excel(archivo, sheet_name="Global 2010")
G2010
# Lectura de hoja "Global 2000"
G2000 = pd.read_excel(archivo, sheet_name="Global 2000")
G2000

,"Global Health Estimates 2021: DALYs by age, sex and cause",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Region:,NaN,NaN,NaN,NaN,Global,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Year:,NaN,NaN,NaN,NaN,2000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,Sex,Both sexes,Male,Female,Male,...,NaN,NaN,Female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,1600,NaN,B.,Intentional injuries,NaN,NaN,83089863.774205,58807843.84866,24282019.925546,4235.333334,...,2376202.45647,1357440.243563,3553.073572,779472.278086,1862746.571592,10391030.843898,7253898.18563,1822739.596923,1184268.079432,984311.357284
219,1610,NaN,NaN,1.,Self-harm,NaN,38803829.2269,24808274.937737,13995554.289163,0,...,1562659.816852,1018020.525966,0,0,437161.731173,6397796.353007,4401362.034539,1227773.427125,807626.623524,723834.119795
220,1620,NaN,NaN,2.,Interpersonal violence,NaN,33398624.062209,25232198.289918,8166425.772291,1971.575644,...,721527.790261,321637.760517,1550.773268,679092.799896,852058.267098,3012838.812642,2512954.145329,536738.033304,335212.281355,235980.720034
221,1630,NaN,NaN,3.,Collective violence and legal intervention,NaN,10887410.485097,8767370.621005,2120039.864092,2263.75769,...,92014.849357,17781.95708,2002.300304,100379.47819,573526.573321,980395.67825,339582.005762,58228.136493,41429.174553,24496.517455
222,1700,NaN,C.,Other COVID-19 pandemic-related outcomes,NaN,NaN,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
# Revisamos cómo se ven los datos de 2021 para identificar la filas que no sirven.
print(G2021.head(10))

  Global Health Estimates 2021: DALYs by age, sex and cause      Unnamed: 1  \
0                                                NaN                    NaN
1                                            Region:                    NaN
2                                              Year:                    NaN
3                                                NaN                    NaN
4                                                NaN                    NaN
5                                                NaN                    NaN
6                             Population (thousands)                    NaN
7                                               Code         Cause of death
8                                                  0                    NaN
9                                                 10                     I.

                                          Unnamed: 2 Unnamed: 3 Unnamed: 4  \
0                                                NaN        NaN        NaN
1                                                NaN        NaN        NaN
2                                                NaN        NaN        NaN
3                                                NaN        NaN        NaN
4                                                NaN        NaN        NaN
5                                                NaN        NaN        NaN
6                                                NaN        NaN        NaN
7                                                NaN        NaN        NaN
8                                         All Causes        NaN        NaN
9  Communicable, maternal, perinatal and nutritio...        NaN        NaN

  Unnamed: 5        Unnamed: 6        Unnamed: 7        Unnamed: 8  \
0        NaN               NaN               NaN               NaN
1     Global               NaN               NaN               NaN
2       2021               NaN               NaN               NaN
3        NaN               NaN               NaN               NaN
4        Sex        Both sexes              Male            Female
5  Age group  Total (all ages)               NaN               NaN
6        NaN       7939383.133       3995066.265       3944316.868
7        NaN               NaN               NaN               NaN
8        NaN  3013734614.04409  1604460303.01016  1409274311.03393
9        NaN  928759077.469129  502669426.712015  426089650.757113

         Unnamed: 9  ...       Unnamed: 15      Unnamed: 16      Unnamed: 17  \
0               NaN  ...               NaN              NaN              NaN
1               NaN  ...               NaN              NaN              NaN
2               NaN  ...               NaN              NaN              NaN
3               NaN  ...               NaN              NaN              NaN
4              Male  ...               NaN              NaN           Female
5         0-28 days  ...             60-69              70+        0-28 days
6       6554.456644  ...         284738.64       206470.376      6087.864699
7               NaN  ...               NaN              NaN              NaN
8  122150960.461571  ...  254254656.531075  291712476.25058  98233253.336727
9  108619505.732124  ...   51640075.468003  53075557.158055   87348406.31804

       Unnamed: 18      Unnamed: 19       Unnamed: 20       Unnamed: 21  \
0              NaN              NaN               NaN               NaN
1              NaN              NaN               NaN               NaN
2              NaN              NaN               NaN               NaN
3              NaN              NaN               NaN               NaN
4              NaN              NaN               NaN               NaN
5      1-59 months             5-14             15-29             30-49
6    321064.753301       657903.377        891073.749       1054417.616
7              NaN              NaN               NaN               NaN
8  124450415.85355  65209479.885556  142984612.172499  270088067.877614
9  94393221.570602  27176421.277304   40345408.474024   62741726.416519

        Unnamed: 22       Unnamed: 23       Unnamed: 24
0               NaN               NaN               NaN
1               NaN               NaN               NaN
2               NaN               NaN               NaN
3               NaN               NaN               NaN
4               NaN               NaN               NaN
5             50-59             60-69               70+
6         427212.97        311085.839        275470.699
7               NaN               NaN               NaN
8  186001068.081479  208431877.562751  313875536.263752
9   31149814.523773   35087909.205697   47846742.394623

[10 rows x 25 columns]

In [6]:
nombres_columnas = G2021.iloc[5].tolist()
print(nombres_columnas)

[nan, nan, nan, nan, nan, 'Age group', 'Total (all ages)', nan, nan, '0-28 days', '1-59 months', '5-14', '15-29', '30-49', '50-59', '60-69', '70+', '0-28 days', '1-59 months', '5-14', '15-29', '30-49', '50-59', '60-69', '70+']

In [7]:
# Dado que las primeras 6 filas no contienen datos útiles, las eliminamos y renombramos las columnas. Esto es, los encabezados están en la fila 5 (index 4)
G2021.columns = nombres_columnas
G2021 = G2021.iloc[6:].reset_index(drop=True)
print(G2021.head(5))

                      NaN             NaN  \
0  Population (thousands)             NaN
1                    Code  Cause of death
2                       0             NaN
3                      10              I.
4                      20             NaN

                                                 NaN  \
0                                                NaN
1                                                NaN
2                                         All Causes
3  Communicable, maternal, perinatal and nutritio...
4                                                 A.

                                 NaN  NaN Age group  Total (all ages)  \
0                                NaN  NaN       NaN       7939383.133
1                                NaN  NaN       NaN               NaN
2                                NaN  NaN       NaN  3013734614.04409
3                                NaN  NaN       NaN  928759077.469129
4  Infectious and parasitic diseases  NaN       NaN  304880090.842236

                NaN               NaN         0-28 days  ...  \
0       3995066.265       3944316.868       6554.456644  ...
1               NaN               NaN               NaN  ...
2  1604460303.01016  1409274311.03393  122150960.461571  ...
3  502669426.712015  426089650.757113  108619505.732124  ...
4  162732717.985024  142147372.857212    5591090.915649  ...

              60-69              70+        0-28 days      1-59 months  \
0         284738.64       206470.376      6087.864699    321064.753301
1               NaN              NaN              NaN              NaN
2  254254656.531075  291712476.25058  98233253.336727  124450415.85355
3   51640075.468003  53075557.158055   87348406.31804  94393221.570602
4    9683874.422252   8672584.539365   4659805.488572  59058201.502689

              5-14             15-29             30-49             50-59  \
0       657903.377        891073.749       1054417.616         427212.97
1              NaN               NaN               NaN               NaN
2  65209479.885556  142984612.172499  270088067.877614  186001068.081479
3  27176421.277304   40345408.474024   62741726.416519   31149814.523773
4  14635737.197366   14471883.215072   21671120.836294    9712354.848535

              60-69               70+
0        311085.839        275470.699
1               NaN               NaN
2  208431877.562751  313875536.263752
3   35087909.205697   47846742.394623
4    8049872.441309    9888397.276761

[5 rows x 25 columns]

In [ ]:
# Aplicamos ffill a las primeras 4 columnas para rellenar los valores faltantes.
# Aplicamos ffill de una columna a la vez, ya que si lo hacemos de una sola vez, se rellenan con el valor de la columna anterior.

columnas_jerarquia = G2021.columns[:4].tolist()
for col in columnas_jerarquia:
    G2021[col] = G2021[col].ffill()

C:\Users\troop\AppData\Local\Temp\ipykernel_21732\2481951157.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  G2021[col] = G2021[col].ffill()

In [11]:
# Igualmente, dado que no nos interesan las columnas correspondientes al total de DALYs por grupo etario para mujeres, hombres y ambos sexos, las eliminamos.
columnas_eliminar = [6, 7, 8]
G2021 = G2021.drop(columns=G2021.columns[columnas_eliminar])

In [12]:
G2021.to_excel('data_raw/DALY_prueba/DALY_ffill_2021.xlsx', index=False, sheet_name='Global 2021')

In [ ]:
# Usamos el método ffill para rellenar las celdas vacías con el valor de la fila anterior.
# Realizamos este proiceso a cada una delas hojas que leímos con anterioridad.

G2021 = G2021.ffill()
G2020 = G2020.ffill()
G2019 = G2019.ffill()
G2015 = G2015.ffill()
G2010 = G2010.ffill()
G2000 = G2000.ffill()

In [ ]:
# Guardamos cada año como un excel limpio en la misma carpeta raw.
G2021.to_excel('data_raw/DALY_prueba/DALY_ffill_2021.xlsx', index=False, sheet_name='Global 2021')
G2020.to_excel('data_raw/DALY_prueba/DALY_ffill_2020.xlsx', index=False, sheet_name='Global 2020')
G2019.to_excel('data_raw/DALY_prueba/DALY_ffill_2019.xlsx', index=False, sheet_name='Global 2019')
G2015.to_excel('data_raw/DALY_prueba/DALY_ffill_2015.xlsx', index=False, sheet_name='Global 2015')
G2010.to_excel('data_raw/DALY_prueba/DALY_ffill_2010.xlsx', index=False, sheet_name='Global 2010')
G2000.to_excel('data_raw/DALY_prueba/DALY_ffill_2000.xlsx', index=False, sheet_name='Global 2000')

## Objetivo de la remodelación y limpieza de datos.

Lo que se observa en los conjuntos de datos que se generaron para cada año es que aún los nombres de las columnas se mantienen como unnamed. Lo que queremos conseguir es que cada columna sea una variable y cada obseración sea una fila. El resultado al que se quiere llegar es el siguiente:

| Nombre de la variables  | Descripción     |
| :-------------: | :------------- |
| categoria_principal | Categoría principal de la enfermedad |
| categoria_nivel1 | Subcategoría |
| categoria_nivel2 | Subsubcategoría (si la hay) |
| nombre_enfermedad | Nombre de la enfermedad. Es el nivel más bajo dentro de las categorías de la OMS.|
| codigo| Código según la OMS. |
| ano | Año correspondiente de la hoja. |
| sexo | Sexo de la persona afectada. |
| edad_min | Límite inferior del rango de edad.|
| edad_max | Límite superior del rango de edad.|
| dalys | Valor numérico de los DALYs para la enfermedad. |

**Tabla 1:** Objetivo de la remodelación y limpieza de datos. Se busca que cada columna sea una variable y cada fila una observación.

Por lo tanto, el siguiente paso será remodelar los conjuntos de datos por año para conseguir un formato adecuado para el análisis posterior. Para esto...

In [ ]:
# Leemos cada file derivado de ffill.
G2021 = 'data_raw/DALY_ffill/DALY_ffill_2021.xlsx'
df = pd.read_excel(G2021)

G2020 = 'data_raw/DALY_ffill/DALY_ffill_2020.xlsx'
df = pd.read_excel(G2020)

G2019 = 'data_raw/DALY_ffill/DALY_ffill_2019.xlsx'
df = pd.read_excel(G2019)

G2015 = 'data_raw/DALY_ffill/DALY_ffill_2015.xlsx'
df = pd.read_excel(G2015)

G2010 = 'data_raw/DALY_ffill/DALY_ffill_2010.xlsx'
df = pd.read_excel(G2010)

G2000 = 'data_raw/DALY_ffill/DALY_ffill_2000.xlsx'
df = pd.read_excel(G2000)