# Remodelación y Limpieza de datos. 
Raíz de que los datos elegidos para el proyecto tienen problemas de multiíndice y filas con celdas vacías, se realizará una limpieza de datos para poder trabajar con ellos.

## Objetivo de la remodelación y limpieza de datos.

Lo que se observa en los conjuntos de datos que se generaron para cada año es que aún los nombres de las columnas se mantienen como unnamed. Lo que queremos conseguir es que cada columna sea una variable y cada obseración sea una fila. El resultado al que se quiere llegar es el siguiente:

| Nombre de la variables  | Descripción     |
| :-------------: | :------------- |
| categoria_principal | Categoría principal de la enfermedad |
| categoria_nivel1 | Subcategoría |
| categoria_nivel2 | Subsubcategoría (si la hay) |
| nombre_enfermedad | Nombre de la enfermedad. Es el nivel más bajo dentro de las categorías de la OMS.|
| codigo| Código según la OMS. |
| ano | Año correspondiente de la hoja. |
| sexo | Sexo de la persona afectada. |
| edad_min | Límite inferior del rango de edad.|
| edad_max | Límite superior del rango de edad.|
| dalys | Valor numérico de los DALYs para la enfermedad. |

**Tabla 1:** Objetivo de la remodelación y limpieza de datos. Se busca que cada columna sea una variable y cada fila una observación.

Por lo tanto, el siguiente paso será remodelar los conjuntos de datos por año para conseguir un formato adecuado para el análisis posterior. Para esto...

In [19]:
# Librerías necesarias
import pandas as pd
import numpy as np

In [57]:
# Definimos el path del archivo .xslsx y los años que nos interesan para el análisis.
archivo = 'data_raw/DALYs/ghe2021_daly_global_new.xlsx'

In [58]:
# Cargamos datos y pandas.
df_2021 = pd.read_excel(archivo, sheet_name="Global 2021")
df_2021

,"Global Health Estimates 2021: DALYs by age, sex and cause",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Region:,NaN,NaN,NaN,NaN,Global,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Year:,NaN,NaN,NaN,NaN,2021,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,Sex,Both sexes,Male,Female,Male,...,NaN,NaN,Female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,1600,NaN,B.,Intentional injuries,NaN,NaN,78657999.918947,57660658.105814,20997341.813133,3398.373065,...,2792668.226074,1657326.433013,2542.22324,582424.387715,1431984.185909,7928250.985026,6475583.292292,2195179.819965,1343364.801955,1038012.176584
219,1610,NaN,NaN,1.,Self-harm,NaN,34146172.515927,23042065.979771,11104106.536156,0,...,1728513.386946,1225272.955303,0,0,317624.509966,4140543.247947,3553250.1246,1442858.316628,907667.507356,742162.82966
220,1620,NaN,NaN,2.,Interpersonal violence,NaN,33204978.083221,25558347.536207,7646630.547013,1742.226793,...,854505.796283,398699.994156,1166.892203,481209.14,593382.354025,2807987.740097,2504098.897254,625948.979053,367136.508996,265700.091701
221,1630,NaN,NaN,3.,Collective violence and legal intervention,NaN,11306849.3198,9060244.589837,2246604.729963,1656.146273,...,209649.042845,33353.483554,1375.331037,101215.247715,520977.321918,979719.996981,418234.270439,126372.524285,68560.785603,30149.255223
222,1700,NaN,C.,Other COVID-19 pandemic-related outcomes,NaN,NaN,50490441.770314,32237870.336044,18252571.434271,2220.873702,...,8174352.936838,7155417.886174,1454.472723,1672.635156,133021.747245,912604.269776,3879304.319166,3210947.613694,4545445.842791,5568120.53372

Empezaremos con la limpieza del conkunto para 2021 y luego se aplicará el mismo proceso a los demás años por medio de un loop.

In [59]:
# Revisamos cómo se ven los datos de 2021 para identificar la filas que no sirven.
print(df_2021.head(10))

  Global Health Estimates 2021: DALYs by age, sex and cause      Unnamed: 1  \
0                                                NaN                    NaN
1                                            Region:                    NaN
2                                              Year:                    NaN
3                                                NaN                    NaN
4                                                NaN                    NaN
5                                                NaN                    NaN
6                             Population (thousands)                    NaN
7                                               Code         Cause of death
8                                                  0                    NaN
9                                                 10                     I.

                                          Unnamed: 2 Unnamed: 3 Unnamed: 4  \
0                                                NaN        NaN        NaN
1                                                NaN        NaN        NaN
2                                                NaN        NaN        NaN
3                                                NaN        NaN        NaN
4                                                NaN        NaN        NaN
5                                                NaN        NaN        NaN
6                                                NaN        NaN        NaN
7                                                NaN        NaN        NaN
8                                         All Causes        NaN        NaN
9  Communicable, maternal, perinatal and nutritio...        NaN        NaN

  Unnamed: 5        Unnamed: 6        Unnamed: 7        Unnamed: 8  \
0        NaN               NaN               NaN               NaN
1     Global               NaN               NaN               NaN
2       2021               NaN               NaN               NaN
3        NaN               NaN               NaN               NaN
4        Sex        Both sexes              Male            Female
5  Age group  Total (all ages)               NaN               NaN
6        NaN       7939383.133       3995066.265       3944316.868
7        NaN               NaN               NaN               NaN
8        NaN  3013734614.04409  1604460303.01016  1409274311.03393
9        NaN  928759077.469129  502669426.712015  426089650.757113

         Unnamed: 9  ...       Unnamed: 15      Unnamed: 16      Unnamed: 17  \
0               NaN  ...               NaN              NaN              NaN
1               NaN  ...               NaN              NaN              NaN
2               NaN  ...               NaN              NaN              NaN
3               NaN  ...               NaN              NaN              NaN
4              Male  ...               NaN              NaN           Female
5         0-28 days  ...             60-69              70+        0-28 days
6       6554.456644  ...         284738.64       206470.376      6087.864699
7               NaN  ...               NaN              NaN              NaN
8  122150960.461571  ...  254254656.531075  291712476.25058  98233253.336727
9  108619505.732124  ...   51640075.468003  53075557.158055   87348406.31804

       Unnamed: 18      Unnamed: 19       Unnamed: 20       Unnamed: 21  \
0              NaN              NaN               NaN               NaN
1              NaN              NaN               NaN               NaN
2              NaN              NaN               NaN               NaN
3              NaN              NaN               NaN               NaN
4              NaN              NaN               NaN               NaN
5      1-59 months             5-14             15-29             30-49
6    321064.753301       657903.377        891073.749       1054417.616
7              NaN              NaN               NaN               NaN
8  124450415.85355  65209479.885556  142984612.172499  270088067.877614
9  94393221.570602  27176421.277304   40345408.474024   62741726.416519

        Unnamed: 22       Unnamed: 23       Unnamed: 24
0               NaN               NaN               NaN
1               NaN               NaN               NaN
2               NaN               NaN               NaN
3               NaN               NaN               NaN
4               NaN               NaN               NaN
5             50-59             60-69               70+
6         427212.97        311085.839        275470.699
7               NaN               NaN               NaN
8  186001068.081479  208431877.562751  313875536.263752
9   31149814.523773   35087909.205697   47846742.394623

[10 rows x 25 columns]

Después de cargar los datos, se observa que las primeras 6 filas no contienen datos útiles, por lo que se eliminarán. Además, los encabezados están en la fila 5 (index 4), por lo que se renombrarán las columnas con los valores de esa fila. El resultado de esta limpieza se guardará en un nuevo archivo Excel para cada año.

In [60]:
# Asignamos bajo la variable "nombres_columnas" los valores de la fila 5 (index 4) para renombrar las columnas.
nombres_columnas = df_2021.iloc[5].tolist()
print(nombres_columnas)

[nan, nan, nan, nan, nan, 'Age group', 'Total (all ages)', nan, nan, '0-28 days', '1-59 months', '5-14', '15-29', '30-49', '50-59', '60-69', '70+', '0-28 days', '1-59 months', '5-14', '15-29', '30-49', '50-59', '60-69', '70+']

In [61]:
# Dado que las primeras 6 filas no contienen datos útiles, las eliminamos y renombramos las columnas. Esto es, los encabezados están en la fila 5 (index 4)
df_2021.columns = nombres_columnas
df_2021 = df_2021.iloc[6:].reset_index(drop=True)
print(df_2021.head(5))

                      NaN             NaN  \
0  Population (thousands)             NaN
1                    Code  Cause of death
2                       0             NaN
3                      10              I.
4                      20             NaN

                                                 NaN  \
0                                                NaN
1                                                NaN
2                                         All Causes
3  Communicable, maternal, perinatal and nutritio...
4                                                 A.

                                 NaN  NaN Age group  Total (all ages)  \
0                                NaN  NaN       NaN       7939383.133
1                                NaN  NaN       NaN               NaN
2                                NaN  NaN       NaN  3013734614.04409
3                                NaN  NaN       NaN  928759077.469129
4  Infectious and parasitic diseases  NaN       NaN  304880090.842236

                NaN               NaN         0-28 days  ...  \
0       3995066.265       3944316.868       6554.456644  ...
1               NaN               NaN               NaN  ...
2  1604460303.01016  1409274311.03393  122150960.461571  ...
3  502669426.712015  426089650.757113  108619505.732124  ...
4  162732717.985024  142147372.857212    5591090.915649  ...

              60-69              70+        0-28 days      1-59 months  \
0         284738.64       206470.376      6087.864699    321064.753301
1               NaN              NaN              NaN              NaN
2  254254656.531075  291712476.25058  98233253.336727  124450415.85355
3   51640075.468003  53075557.158055   87348406.31804  94393221.570602
4    9683874.422252   8672584.539365   4659805.488572  59058201.502689

              5-14             15-29             30-49             50-59  \
0       657903.377        891073.749       1054417.616         427212.97
1              NaN               NaN               NaN               NaN
2  65209479.885556  142984612.172499  270088067.877614  186001068.081479
3  27176421.277304   40345408.474024   62741726.416519   31149814.523773
4  14635737.197366   14471883.215072   21671120.836294    9712354.848535

              60-69               70+
0        311085.839        275470.699
1               NaN               NaN
2  208431877.562751  313875536.263752
3   35087909.205697   47846742.394623
4    8049872.441309    9888397.276761

[5 rows x 25 columns]

In [62]:
# Se utiliza la función "ffill" para rellenar los valores faltantes en las columnas de jerarquía (las primeras 4 columnas) con el último valor no nulo encontrado hacia adelante. Esto es necesario porque en el archivo original, los valores de estas columnas solo se registran una vez para cada grupo, y las filas siguientes dentro del mismo grupo tienen valores nulos.
# Por cada una de las primeras 4 columnas, se aplica ffill para que se rellenen los calores del último valor no nulo hacia adelante.
# Esto asegura que cada fila tenga la información completa de jerarquía.

columnas_jerarquia = df_2021.columns[:4].tolist()
for col in columnas_jerarquia:
    df_2021[col] = df_2021[col].ffill()

C:\Users\troop\AppData\Local\Temp\ipykernel_20196\2461595720.py:7: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_2021[col] = df_2021[col].ffill()

In [63]:
# Por cada columna i dada en la lista df_2021.columns se enumera su índice. 
# Luego, si el nombre es 'Causa', se renombra como 'Causa_i', donde i es el índice de la columna. 
# Si el nombre de la columna no es 'Causa' y no es nulo, se mantiene el mismo nombre. 
# Si el nombre de la columna es nulo, se renombra como 'col_i', donde i es el índice de la columna.

nuevos_nombres = []
for i, col in enumerate(df_2021.columns):
    if col == 'Causa':
        nuevos_nombres.append(f'Causa_{i}')
    else:
        nuevos_nombres.append(col if pd.notna(col) else f'col_{i}')

df_2021.columns = nuevos_nombres

In [64]:
# Renombramos las columnas [0, 1, 2, 3, 4] con nombres más descriptivos.

df_2021 = df_2021.rename(columns={
    df_2021.columns[0]: 'codigo',
    df_2021.columns[1]: 'categoria_principal',
    df_2021.columns[2]: 'categoria_nivel1',
    df_2021.columns[3]: 'categoria_nivel2',
    df_2021.columns[4]: 'causa'
})

In [65]:
# Igualmente, dado que no nos interesan las columnas correspondientes al total de DALYs por grupo etario para mujeres, hombres y ambos sexos, las eliminamos.
columnas_eliminar = [6, 7, 8]
df_2021 = df_2021.drop(columns=df_2021.columns[columnas_eliminar])

In [66]:
# Primero separamos as filas correspondientes a población
# Separamos la fila de población del resto de los datos por si acaso.
poblacion = df_2021['codigo'] == 'Population (thousands)'
poblacion_df = df_2021[poblacion].copy() # Copiamos el dataset sin la fila de población para trabajar con él.

# Definimos el dataset de enfermedades, se acuerdo con que no incluya la fila de población.
df_enfermedades = df_2021[~poblacion].copy()

In [67]:
# También eliminas dos filas de causas totales y una adicional del código.
# Conservamos las filas que no cumplan con el siguiente criterio:
# Para la primer fila...
filas_eliminar = df_enfermedades['categoria_principal'] != 'Cause of death'


# Para la segunda fila...
filas_eliminar2 = df_enfermedades['categoria_nivel2'] != 'All Causes'

# Ambos criterios a la vez...
filas_finales = filas_eliminar & filas_eliminar2

# Aplicamos el filtro al dataset de enfermedades.
df_enfermedades = df_enfermedades[filas_finales].copy()

En el caso de las enfermedades, se acomodará el dataset manualmente. Por lo tanto, generamos un nuevo dataset con las columnas necesarias para el merge posterior con los datos de DALYs organizados por edad y sexo. Estas columnas son: código, categoría principal, categoría nivel 1, categoría nivel 2, causa y Age group.

In [68]:
# Lista de nombres de columnas de jerarquía para un nuevo conjunto de datos.
lista_enfermedades = ['codigo', 'categoria_principal', 'categoria_nivel1', 'categoria_nivel2', 'causa', 'Age group']

# Separamos las columnas correspondientes a enferemdades, junto con sus respectivas columnas de jerarquía.
df_jerarquias = df_enfermedades[lista_enfermedades].copy()

# Revisamos cómo se ven los datos de enfermedades después de la limpieza.
df_jerarquias.head(5)

,codigo,categoria_principal,categoria_nivel1,categoria_nivel2,causa,Age group
3,10,I.,"Communicable, maternal, perinatal and nutritio...",NaN,NaN,NaN
4,20,I.,A.,Infectious and parasitic diseases,NaN,NaN
5,30,I.,A.,1.,Tuberculosis,NaN
6,40,I.,A.,2.,STDs excluding HIV,NaN
7,50,I.,A.,2.,a.,Syphilis

Para reacomodar las variables sexo y edad, se realizará un conjunto de datos adicionales para hombre y mujer. El criterio para separarlos será los rangos de edad. Se mantendrá la columna de código para poder hacer un merge posterior.

In [70]:
# Lista de nombres de columnas de jerarquía para un nuevo conjunto de datos.
lista_edades = ['codigo', '0-28 days', '1-59 months', '5-14', '15-29', '30-49', '50-59', '60-69', '70+']

# Separamos las columnas correspondientes a enferemdades, junto con sus respectivas columnas de jerarquía.
df_dalys = df_enfermedades[lista_edades].copy()

# Revisamos cómo se ven los datos de enfermedades después de la limpieza.
df_dalys.head(5)

,codigo,0-28 days,0-28 days,1-59 months,1-59 months,5-14,5-14,15-29,15-29,30-49,30-49,50-59,50-59,60-69,60-69,70+,70+
3,10,108619505.732124,87348406.31804,107049176.924865,94393221.570602,27194740.771673,27176421.277304,30027294.794567,40345408.474024,76959471.353592,62741726.416519,48103603.104897,31149814.523773,51640075.468003,35087909.205697,53075557.158055,47846742.394623
4,20,5591090.915649,4659805.488572,64964988.33156,59058201.502689,15062423.457068,14635737.197366,15322252.485276,14471883.215072,30067654.390141,21671120.836294,13367848.538517,9712354.848535,9683874.422252,8049872.441309,8672584.539365,9888397.276761
5,30,33.046979,54.595532,4932044.606369,5576673.885822,1094008.747922,1458158.256437,4368796.959188,3330256.044898,10186358.897613,5390537.897352,6338681.258957,3481570.464763,4950131.654464,2912587.56063,3757638.327138,2858887.185742
6,40,2079916.572509,1869392.706819,1227267.274708,735920.579723,38893.844012,37304.795356,150278.020065,223440.796895,258188.750058,482291.741925,59114.981126,118600.470944,27037.423189,58295.805218,19681.292545,46001.979003
7,50,2079916.572509,1869392.706819,1227267.274708,735920.579723,34473.104943,32463.039843,22189.817935,19973.791919,38787.913406,19925.620285,15750.984955,10533.138779,12767.311972,6054.660962,11533.322558,5797.861265

Como el conjunto resultante de este proceso son todos los rangos de edad acomodados como 'hombre' y después el rango correspondiente a 'mujer', se aplicará una función para clasificar los grupos etarios.

In [ ]:
# Definimos los correspondientes a hombres de acuerdo con su posición.
index_hombres = [1, 3, 5, 7, 9, 11, 13, 15]

# Columnas de hombres
df_dalys_hombres = df_dalys.iloc[:, index_hombres].copy()


# Agregar la columna 'codigo' (índice 0)
df_dalys_hombres.insert(0, 'codigo', df_dalys['codigo'])

# Columnas mujeres
# Definimos los correspondientes a mujeres de acuerdo con su posición.
index_mujeres = [2, 4, 6, 8, 10, 12, 14, 16]

# Columnas de hombres
df_dalys_mujeres = df_dalys.iloc[:, index_mujeres].copy()

# Agregar la columna 'codigo' (índice 0)
df_dalys_mujeres.insert(0, 'codigo', df_dalys['codigo'])

In [ ]:
# Verificamos si se seleccionaron dalys de hombres.
print(df_dalys_hombres)

    codigo         0-28 days       1-59 months             5-14  \
3       10  108619505.732124  107049176.924865  27194740.771673
4       20    5591090.915649    64964988.33156  15062423.457068
5       30         33.046979    4932044.606369   1094008.747922
6       40    2079916.572509    1227267.274708     38893.844012
7       50    2079916.572509    1227267.274708     34473.104943
..     ...               ...               ...              ...
212   1600       3398.373065     675358.792972   1896766.420537
213   1610                 0                 0    481815.564468
214   1620       1742.226793     539272.783011    753951.363013
215   1630       1656.146273     136086.009961    660999.493055
216   1700       2220.873702       2272.937035    218175.646506

               15-29            30-49            50-59            60-69  \
3    30027294.794567  76959471.353592  48103603.104897  51640075.468003
4    15322252.485276  30067654.390141  13367848.538517   9683874.422252
5     4368796.959188  10186358.897613   6338681.258957   4950131.654464
6      150278.020065    258188.750058     59114.981126     27037.423189
7       22189.817935     38787.913406     15750.984955     12767.311972
..               ...              ...              ...              ...
212  25549473.254289  19699967.247104   5385699.474766   2792668.226074
213   7371353.326789   9189493.309318   3045617.436946   1728513.386946
214  11940559.054566   9226354.194267   1843262.240471    854505.796283
215   6237560.872934   1284119.743519    496819.797349    209649.042845
216   1564004.801496   8447886.472145   6673538.782149   8174352.936838

                 70+
3    53075557.158055
4     8672584.539365
5     3757638.327138
6       19681.292545
7       11533.322558
..               ...
212   1657326.433013
213   1225272.955303
214    398699.994156
215     33353.483554
216   7155417.886174

[214 rows x 9 columns]

In [ ]:
# Verificamos si se seleccionaron dalys de mujeres.
print(df_dalys_mujeres)

    codigo       0-28 days      1-59 months             5-14            15-29  \
3       10  87348406.31804  94393221.570602  27176421.277304  40345408.474024
4       20  4659805.488572  59058201.502689  14635737.197366  14471883.215072
5       30       54.595532   5576673.885822   1458158.256437   3330256.044898
6       40  1869392.706819    735920.579723     37304.795356    223440.796895
7       50  1869392.706819    735920.579723     32463.039843     19973.791919
..     ...             ...              ...              ...              ...
212   1600      2542.22324    582424.387715   1431984.185909   7928250.985026
213   1610               0                0    317624.509966   4140543.247947
214   1620     1166.892203        481209.14    593382.354025   2807987.740097
215   1630     1375.331037    101215.247715    520977.321918    979719.996981
216   1700     1454.472723      1672.635156    133021.747245    912604.269776

               30-49            50-59            60-69              70+
3    62741726.416519  31149814.523773  35087909.205697  47846742.394623
4    21671120.836294   9712354.848535   8049872.441309   9888397.276761
5     5390537.897352   3481570.464763    2912587.56063   2858887.185742
6      482291.741925    118600.470944     58295.805218     46001.979003
7       19925.620285     10533.138779      6054.660962      5797.861265
..               ...              ...              ...              ...
212   6475583.292292   2195179.819965   1343364.801955   1038012.176584
213     3553250.1246   1442858.316628    907667.507356     742162.82966
214   2504098.897254    625948.979053    367136.508996    265700.091701
215    418234.270439    126372.524285     68560.785603     30149.255223
216   3879304.319166   3210947.613694   4545445.842791    5568120.53372

[214 rows x 9 columns]

In [ ]:
# Hacemos un pd.melt para el dataframe de hombres.
df_dalys_hombres = pd.melt(
    df_dalys_hombres_df,
    id_vars=['codigo'],
    value_vars=columnas_edad,
    var_name='grupo_edad',
    value_name='poblacion'
)

# Para pruebas de visulaización de datos...

In [ ]:
# Conjunto de la hoja de 2021
df_2021.to_excel('data_raw/DALY_def/DALY_2021.xlsx', index=False, sheet_name='Global 2021')

In [ ]:
# Conjunto de datos de jerarquía
df_jerarquias.to_excel('data_raw/DALY_def/DALY_jerarquias2021.xlsx', index=False, sheet_name='Global 2021')

In [71]:
# Conjunto de datos de dalys
df_dalys.to_excel('data_raw/DALY_def/DALY_dalys2021.xlsx', index=False, sheet_name='Global 2021')

In [77]:
df_dalys_hombres.to_excel('data_raw/DALY_def/DALY_dalys_hombres2021.xlsx', index=False, sheet_name='Global 2021')

AttributeError: 'function' object has no attribute 'to_excel'